// src/packages/row/row.tsx
import React, { FunctionComponent } from 'react'
import { DataContext } from './UserContext'
import './row.scss'

export interface RowProps {
  type: string
  justify: string
  align: string
  wrap: string
  gutter: string | number
}
const defaultProps = {
  type: '',
  justify: 'start',
  align: 'flex-start',
  wrap: 'nowrap',
  gutter: '0',
} as RowProps
export const Row: FunctionComponent<Partial<RowProps> & React.HTMLAttributes<HTMLDivElement>> = (
  props
) => {
  const { children, type, justify, align, wrap, gutter } = { ...defaultProps, ...props }
  const prefixCls = 'nut-row'
  const getClass = (prefix: string, type: string) => {
    return prefix ? (type ? `nut-row-${prefix}-${type}` : '') : `nut-row-${type}`
  }
  const getClasses = () => {
    return `
    ${getClass('', type)}
    ${getClass('justify', justify)}
    ${getClass('align', align)}
    ${getClass('flex', wrap)}
    ${prefixCls}
   `
  }
  const parentRow = {
    gutter: gutter,
  }

  return (
    <DataContext.Provider value={parentRow}>
      {/* <div className={`${getClasses()}`}>
          {children}
        </div> */}
      {React.createElement(
        'div',
        {
          className: getClasses(),
        },
        children
      )}
    </DataContext.Provider>
  )
}

Row.defaultProps = defaultProps
Row.displayName = 'NutRow'

// src/packages/__VUE/row/index.vue
<template>
  <view :class="getClasses()">
    <slot></slot>
  </view>
</template>
<script lang="ts">
import { provide } from 'vue';
import { createComponent } from '../../utils/create';
const { componentName, create } = createComponent('row');

export default create({
  props: {
    type: {
      type: String,
      default: ''
    },
    gutter: {
      type: [String, Number],
      default: ''
    },
    justify: {
      type: String,
      default: 'start'
    },
    align: {
      type: String,
      default: 'flex-start'
    },
    wrap: {
      type: String,
      default: 'nowrap'
    }
  },
  setup(props) {
    const prefixCls = componentName;
    provide('gutter', props.gutter);
    const getClass = (prefix: string, type: string) => {
      return prefix
        ? type
          ? `nut-row-${prefix}-${type}`
          : ''
        : `nut-row-${type}`;
    };
    const getClasses = () => {
      return `
              ${getClass('', props.type)}
              ${getClass('justify', props.justify)}
              ${getClass('align', props.align)}
              ${getClass('flex', props.wrap)}
              ${prefixCls}
              `;
    };

    return {
      getClasses
    };
  }
});
</script>
<style lang="scss">
@import 'index.scss';
</style>
