// src/package/signature/src/signature.vue
<template>
    <div class="nut-signature">
    	<div class="nut-signature-inner" ref="wrap">
            <canvas ref="canvas" :height="cHeight" :width="cWidth" v-if="isCanvasSupported"></canvas>
            <p class="nut-signature-unsopport" v-else>{{unSupportTpl}}</p>
        </div>
        <slot></slot>
        <button class="bui-button bui-button-m" @click="clear()">重签</button>
        <button class="bui-button bui-button-m" @click="confirm()">确认</button>
    </div>
</template>
<script>
export default {
    name:'nut-signature',
    props: {
	    lineWidth:  {
            type: Number,
            default: 2
        },
	    strokeStyle:   {
            type: String,
            default: '#000'
        },
	    type: {
            type: String,
            default: 'png'
        },
	    unSupportTpl: {
            type: String,
            default: '对不起，当前浏览器不支持Canvas，无法使用本控件！'
        }
    },
    data() {
        return {
        	cWidth: 0,
            cHeight: 0,
            ctx: null,
            isSupportTouch : ('ontouchstart' in window),
            events: ('ontouchstart' in window) ? ['touchstart', 'touchmove', 'touchend'] : ['mousedown', 'mousemove', 'mouseup']
        };
    },
    computed: {
		isCanvasSupported() {
	        let elem = document.createElement('canvas');
	        return !!(elem.getContext && elem.getContext('2d'));
	    },
    },

    methods: {
	    addEvent() {
	        let _this = this;
	        _this.startEventHandler =  _this.startEventHandler.bind(_this),
	        _this.$refs.canvas.addEventListener(_this.events[0], _this.startEventHandler, false);
	    },

	    startEventHandler(event) {
	        event.preventDefault();

	        let _this = this;
	        _this.ctx.beginPath();
	        _this.ctx.lineWidth = _this.lineWidth;
	        _this.ctx.strokeStyle = _this.strokeStyle;

	        _this.moveEventHandler=  _this.moveEventHandler.bind(_this),
	        _this.endEventHandler= _this.endEventHandler.bind(_this)
	        _this.$refs.canvas.addEventListener(_this.events[1], _this.moveEventHandler, false);
	        _this.$refs.canvas.addEventListener(_this.events[2], _this.endEventHandler, false);

	    },

	    moveEventHandler(event) {
	        event.preventDefault();

	        let _this = this;
	        let evt = _this.isSupportTouch ? event.touches[0] : event;
	        let coverPos = _this.$refs.canvas.getBoundingClientRect();
	        let mouseX = evt.clientX  - coverPos.left;
	        let mouseY = evt.clientY  - coverPos.top;

	        _this.ctx.lineTo(
	            mouseX,
	            mouseY
	        );
	        _this.ctx.stroke();
	    },

	    endEventHandler(event) {
	        event.preventDefault();

	        let _this = this;
	        _this.$refs.canvas.removeEventListener(_this.events[1], _this.moveEventHandler, false);
	        _this.$refs.canvas.removeEventListener(_this.events[2], _this.endEventHandler, false);
	    },

	    clear() {
	        let _this = this;
	        _this.ctx.clearRect(0, 0, _this.cWidth, _this.cHeight);
	    },

	    confirm() {
	        this.onSave(this.$refs.canvas);
	    },

	    onSave(canvas) {
	        let _this = this;
	        let dataurl;
	        switch(_this.type) {
	            case 'png':
	                dataurl = canvas.toDataURL('image/png');
	                break;
	            case 'jpg':
	                dataurl = canvas.toDataURL('image/jpeg', 0.8);
	                break;
	        }
	        this.$emit('confirm', canvas, dataurl);
    	}
    },

    mounted(){
    	let _this = this;
    	if(_this.isCanvasSupported) {
    		_this.ctx = _this.$refs.canvas.getContext('2d');
	        _this.cWidth = _this.$refs.wrap.offsetWidth;
	        _this.cHeight= _this.$refs.wrap.offsetHeight,
			_this.addEvent();
    	}
    }
}
</script>
<style lang="scss">

</style>

// src/packages/signature/signature.tsx
import React, { FunctionComponent, useRef, useState, useEffect } from 'react'
import './signature.scss'
import { Button } from '../button/button'
import bem from '@/utils/bem'

export interface SignatureProps {
  type: String
  lineWidth: Number
  strokeStyle: String
  unSupportTpl: String
  className: string
  confirm?: (canvas: HTMLCanvasElement, dataurl: string) => void
  clear?: () => void
}
const defaultProps = {
  type: 'png',
  lineWidth: 2,
  strokeStyle: '#000',
  unSupportTpl: '对不起，当前浏览器不支持Canvas，无法使用本控件！',
  className: '',
} as SignatureProps
export const Signature: FunctionComponent<
  Partial<SignatureProps> & React.HTMLAttributes<HTMLDivElement>
> = (props) => {
  const { type, lineWidth, strokeStyle, unSupportTpl, className, ...rest } = {
    ...defaultProps,
    ...props,
  }
  const b = bem('signature')
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const wrapRef = useRef<HTMLDivElement>(null)
  const [canvasHeight, setCanvasHeight] = useState(0)
  const [canvasWidth, setCanvasWidth] = useState(0)
  const ctx = useRef<CanvasRenderingContext2D | null>(null)
  const isCanvasSupported = () => {
    let elem = document.createElement('canvas')
    return !!(elem.getContext && elem.getContext('2d'))
  }
  const isSupportTouch = 'ontouchstart' in window
  const events = isSupportTouch
    ? ['touchstart', 'touchmove', 'touchend', 'touchleave']
    : ['mousedown', 'mousemove', 'mouseup', 'mouseleave']

  useEffect(() => {
    if (isCanvasSupported() && canvasRef.current && wrapRef.current) {
      ctx.current = canvasRef.current.getContext('2d')
      setCanvasWidth(wrapRef.current.offsetWidth)
      setCanvasHeight(wrapRef.current.offsetHeight)
      addEvent()
    }
  }, [])

  const startEventHandler = (event: any) => {
    event.preventDefault()
    if (ctx.current && canvasRef.current) {
      ctx.current.beginPath()
      ctx.current.lineWidth = lineWidth as number
      ctx.current.strokeStyle = strokeStyle as string
      canvasRef.current.addEventListener(events[1], moveEventHandler, false)
      canvasRef.current.addEventListener(events[2], endEventHandler, false)
      canvasRef.current.addEventListener(events[3], leaveEventHandler, false)
    }
  }

  const addEvent = () => {
    if (canvasRef.current) {
      canvasRef.current.addEventListener(events[0], startEventHandler, false)
    }
  }

  const moveEventHandler = (event: any) => {
    event.preventDefault()

    let evt = isSupportTouch ? event.touches[0] : event
    if (canvasRef.current && ctx.current) {
      let coverPos = canvasRef.current.getBoundingClientRect()
      let mouseX = evt.clientX - coverPos.left
      let mouseY = evt.clientY - coverPos.top

      ctx.current.lineTo(mouseX, mouseY)
      ctx.current.stroke()
    }
  }

  const endEventHandler = (event: any) => {
    event.preventDefault()
    if (canvasRef.current) {
      canvasRef.current.removeEventListener(events[1], moveEventHandler, false)
      canvasRef.current.removeEventListener(events[2], endEventHandler, false)
    }
  }
  const leaveEventHandler = (event: any) => {
    event.preventDefault()
    if (canvasRef.current) {
      canvasRef.current.removeEventListener(events[1], moveEventHandler, false)
      canvasRef.current.removeEventListener(events[2], endEventHandler, false)
    }
  }
  const clear = () => {
    if (canvasRef.current && ctx.current) {
      canvasRef.current.addEventListener(events[2], endEventHandler, false)
      ctx.current.clearRect(0, 0, canvasWidth, canvasHeight)
      ctx.current.closePath()
    }
    props.clear && props.clear()
  }

  const confirm = () => {
    onSave(canvasRef.current as HTMLCanvasElement)
  }

  const onSave = (canvas: HTMLCanvasElement) => {
    let dataurl
    switch (type) {
      case 'png':
        dataurl = canvas.toDataURL('image/png')
        break
      case 'jpg':
        dataurl = canvas.toDataURL('image/jpeg', 0.8)
        break
    }
    clear()
    props.confirm && props.confirm(canvas, dataurl as string)
  }
  return (
    <div className={`${b()} ${className}`} {...rest}>
      <div className={`${b('inner')}`} ref={wrapRef}>
        {isCanvasSupported() ? (
          <canvas ref={canvasRef} height={canvasHeight} width={canvasWidth}></canvas>
        ) : (
          <p className={`${b('unsopport')}`}>{unSupportTpl}</p>
        )}
      </div>

      <Button className={`${b('btn')}`} type="default" onClick={() => clear()}>
        重签
      </Button>
      <Button className={`${b('btn')}`} type="primary" onClick={() => confirm()}>
        确认
      </Button>
    </div>
  )
}

Signature.defaultProps = defaultProps
Signature.displayName = 'NutSignature'
