// src/packages/__VUE/row/row.vue
<template>
  <view :class="classes">
    <slot></slot>
  </view>
</template>
<script setup lang="ts">
import { provide, computed } from 'vue'
import { LAYOUT_KEY } from '../layout/types'

defineOptions({
  name: 'NutRow'
})

export type RowProps = Partial<{
  type: string
  gutter: string | number
  justify: string
  align: string
  flexWrap: string
}>

const props = withDefaults(defineProps<RowProps>(), {
  type: '',
  gutter: '',
  justify: 'start',
  align: 'flex-start',
  flexWrap: 'nowrap'
})

const prefixCls = 'nut-row'
provide(LAYOUT_KEY, props.gutter)
const getClass = (prefix: string, type: string) => {
  return prefix ? (type ? `nut-row-${prefix}-${type}` : '') : `nut-row-${type}`
}
const classes = computed(() => {
  return [
    prefixCls,
    getClass('', props.type),
    getClass('justify', props.justify),
    getClass('align', props.align),
    getClass('flex', props.flexWrap)
  ]
})
</script>

// src/packages/row/row.tsx
import React, { FunctionComponent } from 'react'
import { DataContext } from './UserContext'
import './row.scss'

export interface RowProps {
  type: string
  justify: string
  align: string
  wrap: string
  gutter: string | number
}
const defaultProps = {
  type: '',
  justify: 'start',
  align: 'flex-start',
  wrap: 'nowrap',
  gutter: '0',
} as RowProps
export const Row: FunctionComponent<Partial<RowProps> & React.HTMLAttributes<HTMLDivElement>> = (
  props
) => {
  const { children, type, justify, align, wrap, gutter } = { ...defaultProps, ...props }
  const prefixCls = 'nut-row'
  const getClass = (prefix: string, type: string) => {
    return prefix ? (type ? `nut-row-${prefix}-${type}` : '') : `nut-row-${type}`
  }
  const getClasses = () => {
    return `
    ${getClass('', type)}
    ${getClass('justify', justify)}
    ${getClass('align', align)}
    ${getClass('flex', wrap)}
    ${prefixCls}
   `
  }
  const parentRow = {
    gutter: gutter,
  }

  return (
    <DataContext.Provider value={parentRow}>
      {/* <div className={`${getClasses()}`}>
          {children}
        </div> */}
      {React.createElement(
        'div',
        {
          className: getClasses(),
        },
        children
      )}
    </DataContext.Provider>
  )
}

Row.defaultProps = defaultProps
Row.displayName = 'NutRow'
