// src/packages/tag/tag.tsx
import React, {
  CSSProperties,
  FunctionComponent,
  MouseEventHandler,
  useEffect,
  useState,
} from 'react'
import './tag.scss'
import classNames from 'classnames'
import Icon from '@/packages/icon'
export interface TagProps {
  type: TagType
  color: string
  textColor: string
  plain: boolean
  round: boolean
  mark: boolean
  closeable: boolean
  isShow: boolean
  prefixCls: string
  onClick: (e: MouseEvent) => void
}

export type TagType = 'default' | 'primary' | 'success' | 'warning' | 'danger'
const defaultProps = {
  type: 'default',
  color: '',
  textColor: '',
  plain: false,
  round: false,
  mark: false,
  closeable: false,
  isShow: true,
  prefixCls: 'nut-tag',
  onClick: (e: MouseEvent) => {},
} as TagProps
export const Tag: FunctionComponent<Partial<TagProps>> = (props) => {
  const {
    color,
    plain,
    type,
    round,
    prefixCls,
    children,
    mark,
    closeable,
    textColor,
    isShow,
    onClick,
  } = {
    ...defaultProps,
    ...props,
  }
  const [btnName, setBtnName] = useState('')
  useEffect(() => {
    setBtnName(classes())
  }, [type, color, textColor, plain, round, mark, closeable, prefixCls, isShow, onClick])
  const classes = () => {
    const prefixCls = 'nut-tag'
    return `${prefixCls}
    ${type ? `${prefixCls}--${type}` : ''}
    ${plain ? `${prefixCls}--plain` : ''}
    ${round ? `${prefixCls}--round` : ''}
    ${mark ? `${prefixCls}--mark` : ''}
    ${closeable ? `${prefixCls}--close` : ''}`
  }
  const handleClick = (e: any) => {
    if (props.onClick) {
      props.onClick(e)
    }
  }
  const getStyle = () => {
    const style: CSSProperties = {}
    if (textColor) {
      style.color = textColor
      if (plain) {
        style.background = '#fff'
      } else {
        if (color) {
          style.background = color
        }
      }
    } else {
      if (color) {
        style.color = '#fff'
        style.background = color
      }
    }
    return style
  }
  return (
    <div>
      {closeable ? (
        isShow ? (
          <div className={`${btnName}`} style={getStyle()} onClick={(e) => handleClick(e)}>
            {children && <span className="text">{children}</span>}
            {closeable && (
              <Icon className="_icon" name="close" size="12" onClick={(e) => handleClick(e)}></Icon>
            )}
          </div>
        ) : (
          ''
        )
      ) : (
        <div className={`${btnName}`} style={getStyle()} onClick={(e) => handleClick(e)}>
          {children && <span className="text">{children}</span>}
        </div>
      )}
    </div>
  )
}

Tag.defaultProps = defaultProps
Tag.displayName = 'NutTag'

// src/packages/__VUE/tag/index.vue
<template>
  <view :class="classes" :style="getStyle()" @click="onClick">
    <slot></slot>
    <nut-icon class="nut-tag--close" v-if="closeable" name="close" size="12" @click="onClose"></nut-icon>
  </view>
</template>

<script lang="ts">
import { PropType, CSSProperties, computed, toRefs } from 'vue';
import { createComponent } from '@/packages/utils/create';
const { componentName, create } = createComponent('tag');
export type TagType = 'primary' | 'success' | 'danger' | 'warning';

export default create({
  props: {
    color: { type: String, default: '' },
    textColor: { type: String, default: '' },
    type: {
      type: String as PropType<TagType>,
      default: 'default'
    },
    plain: {
      type: Boolean,
      default: false
    },
    round: {
      type: Boolean,
      default: false
    },
    mark: {
      type: Boolean,
      default: false
    },
    closeable: {
      type: Boolean,
      default: false
    }
  },
  emits: ['close', 'click'],
  setup(props, { emit }) {
    const { type, color, plain, round, mark, textColor } = toRefs(props);

    const classes = computed(() => {
      const prefixCls = componentName;
      return {
        [prefixCls]: true,
        [`${prefixCls}--${type.value}`]: type.value,
        [`${prefixCls}--plain`]: plain.value,
        [`${prefixCls}--round`]: round.value,
        [`${prefixCls}--mark`]: mark.value
      };
    });

    const getStyle = (): CSSProperties => {
      const style: CSSProperties = {};
      if (color?.value) {
        return {
          background: color.value,
          color: textColor.value
        };
      }
      if (plain.value) {
        return {
          color: '#FA2400',
          background: '#fff',
          border: '1px solid rgba(250,36,0,1)'
        };
      }
      return {
        color: '',
        background: ''
      };
    };

    const onClose = (event: MouseEvent) => {
      event.stopPropagation();
      emit('close', event);
    };

    const onClick = (event: MouseEvent) => {
      event.stopPropagation();
      emit('click', event);
    };

    return {
      classes,
      getStyle,
      onClose,
      onClick
    };
  }
});
</script>
