// src/packages/popup/popup.tsx
import React, {
  FunctionComponent,
  useState,
  useEffect,
  MouseEventHandler,
  MouseEvent,
  EventHandler,
} from 'react'
import { CSSTransition } from 'react-transition-group'
import { OverlayProps, defaultOverlayProps } from '@/packages/overlay/overlay'
import Icon from '@/packages/icon'
import Overlay from '@/packages/overlay'
import classNames from 'classnames'
import bem from '@/utils/bem'
import './popup.scss'
import { EnterHandler, ExitHandler } from 'react-transition-group/Transition'

interface PopupProps extends OverlayProps {
  position: string
  transition: string
  style: React.CSSProperties
  popClass: string
  closeable: boolean
  closeIconPosition: string
  closeIcon: string
  destroyOnClose: boolean
  // teleport: string | HTMLElement
  overlay: boolean
  round: boolean
  onOpen: () => void
  onClose: () => void
  onClick: (e: MouseEvent) => void
  onOpened: (e: HTMLElement) => void
  onClosed: (e: HTMLElement) => void
  onClickOverlay: (e: MouseEvent) => void
  onClickCloseIcon: (e: MouseEvent) => void
}

const defaultProps = {
  position: 'center',
  transition: '',
  style: {},
  popClass: '',
  closeable: false,
  closeIconPosition: 'top-right',
  closeIcon: 'close',
  destroyOnClose: true,
  // teleport: 'body',
  overlay: true,
  round: false,
  onOpen: () => {},
  onClose: () => {},
  onClick: (e: MouseEvent) => {},
  onOpened: (e: HTMLElement) => {},
  onClosed: (e: HTMLElement) => {},
  onClickOverlay: (e: MouseEvent) => {},
  onClickCloseIcon: (e: MouseEvent) => {},
  ...defaultOverlayProps,
} as PopupProps

let _zIndex = 2000

export const Popup: FunctionComponent<Partial<PopupProps> & React.HTMLAttributes<HTMLDivElement>> =
  (props) => {
    const {
      children,
      visible,
      closeOnClickOverlay,
      overlayStyle,
      zIndex,
      lockScroll,
      duration,
      closeable,
      closeIconPosition,
      closeIcon,
      style,
      transition,
      round,
      position,
      popClass,
      destroyOnClose,
      onOpen,
      onClose,
      onClickOverlay,
      onClickCloseIcon,
      onOpened,
      onClosed,
      onClick,
    } = props

    const [index, setIndex] = useState(zIndex ? zIndex : _zIndex)
    const [innerVisible, setInnerVisible] = useState(visible)
    const [showChildren, setShowChildren] = useState(true)
    const [transitionName, setTransitionName] = useState('')

    const b = bem('popup')

    const baseStyle = {
      zIndex: index,
      animationDuration: `${duration}s`,
    }

    const overlayStyles = {
      ...overlayStyle,
      ...baseStyle,
    }

    const popStyles = {
      ...style,
      ...baseStyle,
    }

    const classes = classNames(
      {
        ['round']: round,
        [`popup-${position}`]: true,
        [`${popClass}`]: true,
      },
      b('')
    )

    const closeClasses = classNames({
      'nutui-popup__close-icon': true,
      [`nutui-popup__close-icon--${closeIconPosition}`]: true,
    })

    const open = () => {
      if (!innerVisible) {
        // if(zIndex !== undefined) {
        //   _zIndex = +zIndex;
        // }
        setInnerVisible(visible)
        setIndex(++_zIndex)
      }
      if (destroyOnClose) {
        setShowChildren(true)
      }
      onOpen && onOpen()
    }

    const close = () => {
      if (innerVisible) {
        setInnerVisible(!visible)
        if (destroyOnClose) {
          setTimeout(() => {
            setShowChildren(false)
            onClose && onClose()
          }, Number(duration) * 1000)
        }
      }
    }

    const onHandleClickOverlay = (e: MouseEvent) => {
      if (closeOnClickOverlay) {
        onClickOverlay && onClickOverlay(e)
        close()
      }
    }

    const onHandleClick: MouseEventHandler<HTMLDivElement> = (e: MouseEvent) => {
      onClick && onClick(e)
    }

    const onHandleClickCloseIcon: MouseEventHandler<HTMLDivElement> = (e: MouseEvent) => {
      onClickCloseIcon && onClickCloseIcon(e)
      close()
    }

    const onHandleOpened: EnterHandler<HTMLElement | undefined> | undefined = (e: HTMLElement) => {
      onOpened && onOpened(e)
    }

    const onHandleClosed: ExitHandler<HTMLElement | undefined> | undefined = (e: HTMLElement) => {
      onClosed && onClosed(e)
    }

    useEffect(() => {
      visible && open()
    }, [visible])

    useEffect(() => {
      setTransitionName(transition ? transition : `popup-slide-${position}`)
    }, [position])

    return (
      <React.Fragment>
        <Overlay
          style={overlayStyles}
          visible={innerVisible}
          closeOnClickOverlay={closeOnClickOverlay}
          zIndex={zIndex}
          lockScroll={lockScroll}
          duration={duration}
          onClick={onHandleClickOverlay}
        ></Overlay>
        <CSSTransition
          classNames={transitionName}
          unmountOnExit
          timeout={500}
          in={innerVisible}
          onEntered={onHandleOpened}
          onExited={onHandleClosed}
        >
          <div style={popStyles} className={classes} onClick={onHandleClick}>
            {showChildren ? children : ''}
            {closeable ? (
              <div className={closeClasses} onClick={onHandleClickCloseIcon}>
                <Icon name={closeIcon} size="12px"></Icon>
              </div>
            ) : (
              ''
            )}
          </div>
        </CSSTransition>
      </React.Fragment>
    )
  }

Popup.defaultProps = defaultProps
Popup.displayName = 'NutPopup'

// src/packages/popup/index.vue
<template>
  <Teleport :to="teleport">
    <nut-overlay
      v-if="overlay"
      :visible="visible"
      :class="overlayClass"
      :style="overlayStyle"
      :z-index="zIndex"
      :duration="duration"
      @click="onClickOverlay"
    />
    <Transition
      :name="transitionName"
      @after-enter="onOpened"
      @after-leave="onClosed"
    >
      <view
        v-show="visible"
        :class="classes"
        :style="popStyle"
        @click="onClick"
      >
        <slot v-if="showSlot"></slot>
        <nut-icon
          v-if="closeable"
          @click="onClickCloseIcon"
          :name="closeIcon"
          size="12px"
          class="nutui-popup__close-icon"
          :class="'nutui-popup__close-icon--' + closeIconPosition"
        >
        </nut-icon>
      </view>
    </Transition>
  </Teleport>
</template>
<script lang="ts">
import {
  onMounted,
  onBeforeMount,
  onBeforeUnmount,
  onActivated,
  onDeactivated,
  watch,
  computed,
  reactive,
  PropType,
  CSSProperties,
  toRefs
} from 'vue';
import { useLockScroll } from './use-lock-scroll';
import { overlayProps } from './../overlay/index.vue';
import overlay from '@/packages/overlay/index.vue';
import { createComponent } from '@/utils/create';
const { componentName, create } = createComponent('popup');

let _zIndex = 2000;

export const popupProps = {
  ...overlayProps,
  position: {
    type: String,
    default: 'center'
  },

  transition: String,

  style: {
    type: Object as PropType<CSSProperties>
  },

  popClass: {
    type: String,
    default: ''
  },

  closeable: {
    type: Boolean,
    default: false
  },

  closeIconPosition: {
    type: String,
    default: 'top-right'
  },

  closeIcon: {
    type: String,
    default: 'close'
  },

  destroyOnClose: {
    type: Boolean,
    default: true
  },

  teleport: {
    type: [String, Element],
    default: 'body'
  },

  overlay: {
    type: Boolean,
    default: true
  },

  round: {
    type: Boolean,
    default: false
  }
};
export default create({
  children: [overlay],
  props: {
    ...popupProps
  },
  emits: [
    'click',
    'click-close-icon',
    'open',
    'close',
    'opend',
    'closed',
    'update:visible',
    'click-overlay'
  ],

  setup(props, { emit }) {
    const state = reactive({
      zIndex: 1,
      showSlot: true,
      transitionName: `popup-fade-${props.position}`,
      overLayCount: 1,
      keepAlive: false
    });

    const [lockScroll, unlockScroll] = useLockScroll(() => props.lockScroll);

    const classes = computed(() => {
      const prefixCls = componentName;
      return {
        [prefixCls]: true,
        ['round']: props.round,
        [`popup-${props.position}`]: true,
        [props.popClass]: true
      };
    });

    const popStyle = computed(() => {
      return {
        zIndex: state.zIndex,
        animationDuration: props.duration ? `${props.duration}s` : 'initial',
        ...props.style
      };
    });

    const open = () => {
      if (!props.visible) {
        if (props.zIndex !== undefined) {
          _zIndex = Number(props.zIndex);
        }
        emit('update:visible', true);
        lockScroll();
        state.zIndex = ++_zIndex;
      }
      if (props.destroyOnClose) {
        state.showSlot = true;
      }
      emit('open');
    };

    const close = () => {
      if (props.visible) {
        unlockScroll();
        emit('update:visible', false);
        if (props.destroyOnClose) {
          setTimeout(() => {
            state.showSlot = false;
            emit('close');
          }, +props.duration * 1000);
        }
      }
    };

    const onClick = (e: Event) => {
      emit('click', e);
    };

    const onClickCloseIcon = (e: Event) => {
      emit('click-close-icon', e);
      close();
    };

    const onClickOverlay = (e: Event) => {
      if (props.closeOnClickOverlay) {
        emit('click-overlay', e);
        close();
      }
    };

    const onOpened = (e: Event) => {
      emit('opend', e);
    };

    const onClosed = (e: Event) => {
      emit('closed', e);
    };

    onMounted(() => {
      props.transition
        ? (state.transitionName = props.transition)
        : (state.transitionName = `popup-slide-${props.position}`);

      props.visible && open();
    });

    onBeforeUnmount(() => {
      props.visible && close();
    });

    onBeforeMount(() => {
      if (props.visible) {
        unlockScroll();
      }
    });

    onActivated(() => {
      if (state.keepAlive) {
        emit('update:visible', true);
        state.keepAlive = false;
      }
    });

    onDeactivated(() => {
      if (props.visible) {
        close();
        state.keepAlive = true;
      }
    });

    watch(
      () => props.visible,
      value => {
        if (value) {
          open();
        } else {
          close();
        }
      }
    );

    watch(
      () => props.position,
      value => {
        value === 'center'
          ? (state.transitionName = 'popup-fade')
          : (state.transitionName = `popup-slide-${value}`);
      }
    );

    return {
      ...toRefs(state),
      popStyle,
      classes,
      onClick,
      onClickCloseIcon,
      onClickOverlay,
      onOpened,
      onClosed
    };
  }
});
</script>

<style lang="scss">
@import 'index.scss';
</style>
