// src/packages/textarea/textarea.tsx
import React, { FunctionComponent, useEffect, useState } from 'react'
import './textarea.scss'
import bem from '@/utils/bem'

export interface TextAreaProps {
  defaultValue: string | number | any
  textAlign?: string | any
  limitshow?: boolean
  maxlength?: any
  rows?: any
  placeholder?: string
  readonly?: boolean
  disabled?: boolean
  autosize?: boolean
  change?: (value: any, event: Event) => void
  blur?: (event: Event) => void
  focus?: (event: Event) => void
}
const defaultProps = {
  defaultValue: '',
  textAlign: 'left',
  limitshow: false,
  maxlength: '',
  rows: '',
  placeholder: '请输入内容',
  readonly: false,
  disabled: false,
  autosize: false,
} as TextAreaProps
export const TextArea: FunctionComponent<
  Partial<TextAreaProps> & React.HTMLAttributes<HTMLDivElement>
> = (props) => {
  const {
    children,
    defaultValue,
    textAlign,
    limitshow,
    maxlength,
    rows,
    placeholder,
    readonly,
    disabled,
    autosize,
    change,
    blur,
    focus,
  } = { ...defaultProps, ...props }

  const textareaBem = bem('textarea')
  const [inputValue, SetInputValue] = useState('')

  useEffect(() => {
    if (defaultValue) {
      SetInputValue(defaultValue)
    }
  }, [defaultValue])

  const textChange = (event: Event) => {
    const text = event.target as any
    SetInputValue(text.value)
    if (change) {
      change(text, event)
    }
  }

  const textFocus = (event: Event) => {
    if (disabled) return
    if (readonly) return
    if (focus) {
      focus(event)
    }
  }

  const textBlur = (event: Event) => {
    if (disabled) return
    if (readonly) return
    const text = event.target as any
    if (change) {
      change(text, event)
    }
    if (blur) {
      blur(event)
    }
    //  emitChange(value, event)
    //  emit('blur', event)
  }

  return (
    <div className={`${textareaBem()} ${disabled ? textareaBem('disabled') : ''}`}>
      <textarea
        className={textareaBem('textarea')}
        style={{ textAlign: textAlign, resize: `${autosize ? 'vertical' : 'none'}` }}
        disabled={disabled}
        readOnly={readonly}
        value={inputValue}
        onChange={(e: any) => {
          textChange(e)
        }}
        onBlur={(e: any) => {
          textBlur(e)
        }}
        onFocus={(e: any) => {
          textFocus(e)
        }}
        rows={rows}
        maxLength={maxlength}
        placeholder={placeholder}
      />
      {limitshow ? (
        <div className={textareaBem('limit')}>
          {inputValue.length}/{maxlength}
        </div>
      ) : null}
    </div>
  )
}

TextArea.defaultProps = defaultProps
TextArea.displayName = 'NutTextArea'

// src/packages/textarea/index.vue
<template>
  <view :class="classes">
    <textarea
      class="nut-textarea__textarea"
      :style="styles"
      :rows="rows"
      :disabled="disabled"
      :readonly="readonly"
      :value="modelValue"
      @input="change"
      @blur="blur"
      @focus="focus"
      :maxlength="maxLength"
      :placeholder="placeholder"
    />
    <view class="nut-textarea__limit" v-if="limitShow">
      {{ modelValue.length }}/{{ maxLength }}</view
    >
  </view>
</template>
<script lang="ts">
import { computed, watch } from 'vue';
import { createComponent } from '@/utils/create';

const { componentName, create } = createComponent('textarea');

export default create({
  props: {
    modelValue: {
      type: [String, Number],
      default: ''
    },
    textAlign: {
      type: String,
      default: 'left'
    },
    limitShow: {
      type: Boolean,
      default: false
    },
    maxLength: {
      type: [String, Number],
      default: ''
    },
    rows: {
      type: [String, Number],
      default: ''
    },
    placeholder: {
      type: String,
      default: '请输入内容'
    },
    readonly: {
      type: Boolean,
      default: false
    },
    disabled: {
      type: Boolean,
      default: false
    },
    autosize: {
      type: Boolean,
      default: false
    }
  },

  emits: ['update:modelValue', 'change', 'blur', 'focus'],

  setup(props, { emit }) {
    const classes = computed(() => {
      const prefixCls = componentName;
      return {
        [prefixCls]: true,
        [`${prefixCls}--disabled`]: props.disabled
      };
    });

    const styles = computed(() => {
      return {
        textAlign: props.textAlign,
        resize: props.autosize ? 'vertical' : 'none'
      };
    });

    const emitChange = (value: string, event: Event) => {
      if (props.maxLength && value.length > Number(props.maxLength)) {
        value = value.substring(0, Number(props.maxLength));
      }
      emit('change', value, event);
      emit('update:modelValue', value, event);
    };

    const change = (event: Event) => {
      const input = event.target as HTMLInputElement;
      emitChange(input.value, event);
    };

    const focus = (event: Event) => {
      if (props.disabled) return;
      if (props.readonly) return;
      emit('focus', event);
    };

    const blur = (event: Event) => {
      if (props.disabled) return;
      if (props.readonly) return;
      const input = event.target as HTMLInputElement;

      let value = input.value;

      emitChange(value, event);
      emit('blur', event);
    };

    return {
      classes,
      styles,
      change,
      focus,
      blur
    };
  }
});
</script>

<style lang="scss">
@import 'index.scss';
</style>
