// src/packages/__VUE/overlay/overlay.vue
<template>
  <Transition name="overlay-fade">
    <view v-show="visible" :class="classes" :style="style" @click.stop="onClick">
      <slot></slot>
    </view>
  </Transition>
</template>
<script setup lang="ts">
import { CSSProperties, computed, watchEffect } from 'vue'
import { useLockScroll } from '@/packages/utils'

defineOptions({
  name: 'NutOverlay'
})

export type OverlayProps = Partial<{
  visible: boolean
  zIndex: string | number
  duration: string | number
  lockScroll: boolean
  overlayClass: string
  overlayStyle: CSSProperties
  closeOnClickOverlay: boolean
}>

const props = withDefaults(defineProps<OverlayProps>(), {
  visible: false,
  zIndex: 2000,
  duration: 0.3,
  lockScroll: true,
  overlayClass: '',
  closeOnClickOverlay: true
})

const emit = defineEmits(['click', 'update:visible'])

const [lock, unlock] = useLockScroll(() => props.lockScroll)

const classes = computed(() => {
  const prefixCls = 'nut-overlay'
  return {
    [prefixCls]: true,
    [props.overlayClass]: true
  }
})

const style = computed(() => {
  return {
    transitionDuration: `${props.duration}s`,
    zIndex: props.zIndex,
    ...props.overlayStyle
  }
})

watchEffect(() => {
  props.visible ? lock() : unlock()
})

const onClick = (e: MouseEvent) => {
  emit('click', e)
  if (props.closeOnClickOverlay) {
    emit('update:visible', false)
  }
}
</script>

// src/packages/overlay/overlay.tsx
import React, { FunctionComponent, MouseEventHandler, useEffect, useRef, useState } from 'react'
import bem from '@/utils/bem'
import classNames from 'classnames'
import './overlay.scss'

export interface OverlayProps {
  zIndex: number
  duration: number
  overlayClass: string
  overlayStyle: React.CSSProperties
  closeOnClickOverlay: boolean
  visible: boolean
  lockScroll: boolean
}
export const defaultOverlayProps = {
  zIndex: 2000,
  duration: 0.3,
  overlayClass: '',
  closeOnClickOverlay: true,
  visible: false,
  lockScroll: true,
  overlayStyle: {},
} as OverlayProps
export const Overlay: FunctionComponent<
  Partial<OverlayProps> & React.HTMLAttributes<HTMLDivElement>
> = (props) => {
  const [show, setShow] = useState(false)
  const renderRef = useRef(true)
  const intervalRef = useRef(0)
  const {
    children,
    zIndex,
    duration,
    overlayClass,
    closeOnClickOverlay,
    visible,
    lockScroll,
    overlayStyle,
    ...rest
  } = {
    ...defaultOverlayProps,
    ...props,
  }

  useEffect(() => {
    setShow(false)
    lock()
  }, [visible])

  useEffect(() => {
    return () => {
      clearTimeout(intervalRef.current)
      document.body.classList.remove('nut-overflow-hidden')
    }
  }, [])

  const b = bem('overlay')

  const classes = classNames(
    {
      'overlay-fade-leave-active': !renderRef.current && !visible,
      'overlay-fade-enter-active': visible,
      'first-render': renderRef.current && !visible,
      'hidden-render': show,
    },
    overlayClass,
    b('')
  )

  const styles = {
    zIndex: zIndex,
    animationDuration: `${props.duration}s`,
    ...overlayStyle,
  }

  const lock = () => {
    if (lockScroll && visible) {
      document.body.classList.add('nut-overflow-hidden')
    } else {
      document.body.classList.remove('nut-overflow-hidden')
    }
  }

  const handleClick: MouseEventHandler<HTMLDivElement> = (e) => {
    if (closeOnClickOverlay) {
      props.onClick && props.onClick(e)
      renderRef.current = false
      let id = setTimeout(() => {
        setShow(true)
      }, duration * 1000 * 0.8)
      intervalRef.current = id
    }
  }

  return (
    <React.Fragment>
      <div className={classes} style={styles} {...rest} onClick={handleClick}>
        {children}
      </div>
    </React.Fragment>
  )
}

Overlay.defaultProps = defaultOverlayProps
Overlay.displayName = 'NutOverlay'
