// src/packages/divider/divider.tsx
import React, { FunctionComponent } from 'react'
import './divider.scss'
import bem from '@/utils/bem'
import classNames from 'classnames'

export interface DividerProps {
  contentPosition: string
  dashed: boolean
  hairline: boolean
  styles?: React.CSSProperties
}
const defaultProps = {
  contentPosition: 'center',
  dashed: false,
  hairline: true,
} as DividerProps
export const Divider: FunctionComponent<
  Partial<DividerProps> & React.HTMLAttributes<HTMLDivElement>
> = (props) => {
  const { children, contentPosition, dashed, hairline, styles } = { ...defaultProps, ...props }
  const dividerBem = bem('divider')
  const classes = classNames({
    [dividerBem()]: true,
    [dividerBem('center')]: children,
    [dividerBem('left')]: contentPosition === 'left',
    [dividerBem('right')]: contentPosition === 'right',
    [dividerBem('dashed')]: dashed,
    [dividerBem('hairline')]: hairline,
  })
  return (
    <div className={classes} style={styles}>
      {children}
    </div>
  )
}

Divider.defaultProps = defaultProps
Divider.displayName = 'NutDivider'

// src/packages/__VUE/divider/divider.vue
<template>
  <view :class="classes">
    <slot v-if="direction === 'horizontal'"></slot>
  </view>
</template>
<script setup lang="ts">
import { computed } from 'vue'
import { DividerDirection, DividerPosition } from './types'

defineOptions({
  name: 'NutDivider'
})

export type DividerProps = Partial<{
  contentPosition: DividerPosition
  dashed: boolean
  hairline: boolean
  direction: DividerDirection
}>

const props = withDefaults(defineProps<DividerProps>(), {
  contentPosition: 'center',
  dashed: false,
  hairline: true,
  direction: 'horizontal'
})

const slots = defineSlots()

const classes = computed(() => {
  const prefixCls = 'nut-divider'
  if (props.direction === 'horizontal') {
    return {
      [prefixCls]: true,
      [`${prefixCls}-center`]: slots.default,
      [`${prefixCls}-left`]: props.contentPosition === 'left',
      [`${prefixCls}-right`]: props.contentPosition === 'right',
      [`${prefixCls}-dashed`]: props.dashed,
      [`${prefixCls}-hairline`]: props.hairline
    }
  } else {
    return {
      [prefixCls]: true,
      [`${prefixCls}-vertical`]: props.direction === 'vertical'
    }
  }
})
</script>
