// src/packages/divider/divider.tsx
import React, { FunctionComponent } from 'react'
import './divider.scss'
import bem from '@/utils/bem'
import classNames from 'classnames'

export interface DividerProps {
  contentPosition: string
  dashed: boolean
  hairline: boolean
  styles?: React.CSSProperties
}
const defaultProps = {
  contentPosition: 'center',
  dashed: false,
  hairline: true,
} as DividerProps
export const Divider: FunctionComponent<
  Partial<DividerProps> & React.HTMLAttributes<HTMLDivElement>
> = (props) => {
  const { children, contentPosition, dashed, hairline, styles } = { ...defaultProps, ...props }
  const dividerBem = bem('divider')
  const classes = classNames({
    [dividerBem()]: true,
    [dividerBem('center')]: children,
    [dividerBem('left')]: contentPosition === 'left',
    [dividerBem('right')]: contentPosition === 'right',
    [dividerBem('dashed')]: dashed,
    [dividerBem('hairline')]: hairline,
  })
  return (
    <div className={classes} style={styles}>
      {children}
    </div>
  )
}

Divider.defaultProps = defaultProps
Divider.displayName = 'NutDivider'

// src/packages/__VUE/divider/index.vue
<template>
  <div :class="classes">
    <slot></slot>
  </div>
</template>
<script lang="ts">
import { computed, onMounted } from 'vue';
import { createComponent } from '@/packages/utils/create';
const { componentName, create } = createComponent('divider');

export default create({
  props: {
    contentPosition: {
      type: String,
      default: 'center'
    },
    dashed: {
      type: Boolean,
      default: false
    },
    hairline: {
      type: Boolean,
      default: true
    }
  },
  components: {},

  setup(props, context) {
    const classes = computed(() => {
      const prefixCls = componentName;
      return {
        [prefixCls]: true,
        [`${prefixCls}-center`]: context.slots.default,
        [`${prefixCls}-left`]: props.contentPosition === 'left',
        [`${prefixCls}-right`]: props.contentPosition === 'right',
        [`${prefixCls}-dashed`]: props.dashed,
        [`${prefixCls}-hairline`]: props.hairline
      };
    });

    return { classes };
  }
});
</script>
