// src/packages/badge/badge.tsx
import React, {
  CSSProperties,
  FunctionComponent,
  MouseEventHandler,
  useEffect,
  useState,
} from 'react'
import './badge.scss'
import Icon from '@/packages/icon'
export interface BadgeProps {
  value: any
  dot: boolean
  max: Number
  top: string
  right: string
  zIndex: string
  color: string
  icons: any
}

export type BadgeType = 'default' | 'primary' | 'success' | 'warning' | 'danger'
const defaultProps = {
  value: '',
  dot: false,
  max: 10000,
  top: '0',
  right: '0',
  zIndex: '0',
  color: '',
  icons: '',
} as BadgeProps
export const Badge: FunctionComponent<Partial<BadgeProps>> = (props) => {
  const { value, children, dot, max, top, right, zIndex, color, icons } = {
    ...defaultProps,
    ...props,
  }
  const content = () => {
    if (dot) return
    const value = props.value
    const max = props.max
    if (typeof value === 'number' && typeof max === 'number') {
      return max < value ? `${max}+` : value
    }
    return value
  }
  const getStyle = () => {
    const style: CSSProperties = {}
    style.top = `${top}px`
    style.right = `${right}px`
    style.zIndex = zIndex
    style.background = color
    return style
  }
  return (
    <div className="nut-badge">
      {icons != '' && (
        <div className="slot-icons">
          <Icon className="_icon" name={icons} color="#ffffff" size="12"></Icon>
        </div>
      )}
      <div>{children}</div>
      <div className={`${dot ? 'is-dot' : ''} nut-badge__content sup`} style={getStyle()}>
        {content()}
      </div>
    </div>
  )
}

Badge.defaultProps = defaultProps
Badge.displayName = 'NutBadge'

// src/packages/__VUE/badge/badge.vue
<template>
  <view class="nut-badge">
    <view v-show="!hidden && !dot && $slots.icon" class="nut-badge__icon" :style="style">
      <slot name="icon"></slot>
    </view>
    <slot></slot>
    <view
      v-show="!hidden && (content || dot)"
      class="nut-badge__content nut-badge__content--sup"
      :class="{ 'nut-badge__content--dot': dot, 'nut-badge__content--bubble': !dot && bubble }"
      :style="style"
    >
      {{ content }}
    </view>
  </view>
</template>

<script setup lang="ts">
import { computed } from 'vue'

defineOptions({
  name: 'NutBadge'
})

export type BadgeProps = Partial<{
  value: string | number
  max: number
  dot: boolean
  bubble: boolean
  hidden: boolean
  top: string
  right: string
  zIndex: number
  color: string
}>

const props = withDefaults(defineProps<BadgeProps>(), {
  max: 10000,
  dot: false,
  bubble: false,
  hidden: false,
  top: '0',
  right: '0',
  zIndex: 9,
  color: ''
})

const style = computed(() => {
  return {
    top: `${props.top}px`,
    right: `${props.right}px`,
    zIndex: props.zIndex,
    background: props.color
  }
})

const content = computed(() => {
  if (props.dot) return
  const value = props.value
  const max = props.max
  if (typeof value === 'number' && typeof max === 'number') {
    return max < value ? `${max}+` : value
  }
  return value
})
</script>
