// src/packages/badge/badge.tsx
import React, {
  CSSProperties,
  FunctionComponent,
  MouseEventHandler,
  useEffect,
  useState,
} from 'react'
import './badge.scss'
import Icon from '@/packages/icon'
export interface BadgeProps {
  value: any
  dot: boolean
  max: Number
  top: string
  right: string
  zIndex: string
  color: string
  icons: any
}

export type BadgeType = 'default' | 'primary' | 'success' | 'warning' | 'danger'
const defaultProps = {
  value: '',
  dot: false,
  max: 10000,
  top: '0',
  right: '0',
  zIndex: '0',
  color: '',
  icons: '',
} as BadgeProps
export const Badge: FunctionComponent<Partial<BadgeProps>> = (props) => {
  const { value, children, dot, max, top, right, zIndex, color, icons } = {
    ...defaultProps,
    ...props,
  }
  const content = () => {
    if (dot) return
    const value = props.value
    const max = props.max
    if (typeof value === 'number' && typeof max === 'number') {
      return max < value ? `${max}+` : value
    }
    return value
  }
  const getStyle = () => {
    const style: CSSProperties = {}
    style.top = `${top}px`
    style.right = `${right}px`
    style.zIndex = zIndex
    style.background = color
    return style
  }
  return (
    <div className="nut-badge">
      {icons != '' && (
        <div className="slot-icons">
          <Icon className="_icon" name={icons} color="#ffffff" size="12"></Icon>
        </div>
      )}
      <div>{children}</div>
      <div className={`${dot ? 'is-dot' : ''} nut-badge__content sup`} style={getStyle()}>
        {content()}
      </div>
    </div>
  )
}

Badge.defaultProps = defaultProps
Badge.displayName = 'NutBadge'

// src/packages/__VUE/badge/index.vue
<template>
  <view class="nut-badge">
    <view class="nut-badge__icon" v-show="!hidden && !dot" :style="stl">
      <slot name="icons"></slot>
    </view>
    <slot></slot>
    <view
      v-show="!hidden && (content || dot)"
      v-text="content"
      class="nut-badge__content nut-badge__content--sup"
      :class="{ 'nut-badge__content--dot': dot }"
      :style="stl"
    >
    </view>
  </view>
</template>

<script lang="ts">
import { computed, reactive } from 'vue';
import { createComponent } from '@/packages/utils/create';
const { create } = createComponent('badge');
export default /* @__PURE__ */ create({
  props: {
    value: {
      type: [String, Number]
    },
    max: {
      type: Number,
      default: 10000
    },
    dot: {
      type: Boolean,
      default: false
    },
    hidden: {
      type: Boolean,
      default: false
    },
    top: {
      type: String,
      default: '0'
    },
    right: {
      type: String,
      default: '0'
    },
    zIndex: {
      type: Number,
      default: 9
    },
    color: {
      type: String,
      default: ''
    }
  },

  setup(props) {
    const state = reactive({});

    const stl = computed(() => {
      return {
        top: `${props.top}px`,
        right: `${props.right}px`,
        zIndex: props.zIndex,
        background: props.color
      };
    });

    const content = computed(() => {
      if (props.dot) return;
      const value = props.value;
      const max = props.max;
      if (typeof value === 'number' && typeof max === 'number') {
        return max < value ? `${max}+` : value;
      }
      return value;
    });

    return {
      state,
      stl,
      content
    };
  }
});
</script>
