// src/packages/fixednav/fixednav.tsx
import React, { FunctionComponent, useState, useEffect, MouseEvent, HTMLProps } from 'react'
import { Icon } from '../icon/icon'
import { Overlay } from '../overlay/overlay'
import classNames from 'classnames'

import './fixednav.scss'

export interface FixedNavProps {
  prefixCls: string
  visible: boolean
  overlay: boolean
  navList: Array<object>
  activeText: string
  unActiveText: string
  position: object
  type: string
  change: Function
  selected: Function
  slotList: HTMLProps<HTMLElement>
  slotBtn: HTMLProps<HTMLElement>
}

const defaultProps = {
  prefixCls: 'nut-fixednav',
  activeText: '收起导航',
  unActiveText: '快速导航',
  position: {
    top: 'auto',
    bottom: 'auto',
  },
  type: 'right',
} as FixedNavProps

export const FixedNav: FunctionComponent<
  Partial<FixedNavProps> & React.HTMLAttributes<HTMLDivElement>
> = (props) => {
  const {
    prefixCls,
    children,
    overlay,
    visible,
    navList,
    activeText,
    unActiveText,
    position,
    change,
    selected,
    type,
    slotList,
    slotBtn,
  } = { ...defaultProps, ...props }

  const selectCb = (event: MouseEvent, item: any) => {
    selected(item, event)
  }

  const updateValue = (value: boolean = !visible) => {
    change(value)
  }

  const [classNames, setClassNames] = useState('')

  const classes = () => {
    return `${prefixCls} ${type} ${visible ? 'active' : ''}`
  }

  useEffect(() => {
    setClassNames(classes())
  }, [visible])

  return (
    <div className={`${classNames}`} style={position}>
      {overlay && (
        <Overlay visible={visible} zIndex={200} onClick={() => updateValue(false)}></Overlay>
      )}
      <div className="list">
        {slotList ? (
          slotList
        ) : (
          <div className="nut-fixednav__list">
            {navList.map((item: any, index) => {
              return (
                <div
                  className="nut-fixednav__list-item"
                  onClick={(event) => selectCb(event, item)}
                  key={item.id || index}
                >
                  <img src={item.icon} />
                  <div className="span">{item.text}</div>
                  {item.num && <div className="b">{item.num}</div>}
                </div>
              )
            })}
          </div>
        )}
      </div>

      <div className="nut-fixednav__btn" onClick={() => updateValue()}>
        {slotBtn ? (
          slotBtn
        ) : (
          <>
            <Icon name="left" color="#fff" />
            <div className="text">{visible ? activeText : unActiveText}</div>
          </>
        )}
      </div>
    </div>
  )
}

FixedNav.defaultProps = defaultProps
FixedNav.displayName = 'NutFixedNav'

// src/packages/__VUE/fixednav/index.vue
<template>
  <view :class="classes" :style="position">
    <nut-overlay v-if="overlay" :visible="visible" :z-index="200" @click="updateValue(false)" />
    <slot name="list">
      <view class="nut-fixed-nav__list">
        <view
          v-for="(item, index) in navList"
          :key="item.id || index"
          class="nut-fixed-nav__list-item"
          :class="{ active: item.id == current }"
          @click="selected(item, $event)"
        >
          <img :src="item.icon" />
          <view class="span">{{ item.text }}</view>
          <view v-if="item.num" class="b">{{ item.num }}</view>
        </view>
      </view>
    </slot>
    <div class="nut-fixed-nav__btn" @click="updateValue()">
      <slot name="btn">
        <Left color="#fff" />
        <view class="text">
          {{ visible ? activeText || translate('activeText') : unActiveText || translate('unActiveText') }}
        </view>
      </slot>
    </div>
  </view>
</template>
<script lang="ts">
import { PropType, computed, ref } from 'vue';
import { Left } from '@nutui/icons-vue';
import NutOverlay from '../overlay/index.vue';
import { createComponent } from '@/packages/utils/create';
import { useLocale } from '@/packages/utils/useLocale';
const { create } = createComponent('fixed-nav');

const cN = 'NutFixedNav';

export default create({
  components: {
    NutOverlay,
    Left
  },
  props: {
    visible: {
      type: Boolean,
      default: false
    },
    overlay: {
      type: Boolean,
      default: true
    },
    navList: {
      default: () => [],
      type: Array as PropType<any[]>
    },
    activeColor: {
      default: '',
      type: String
    },
    activeText: {
      default: '',
      type: String
    },
    unActiveText: {
      default: '',
      type: String
    },
    position: {
      default: () => {
        return {
          top: 'auto',
          bottom: 'auto'
        };
      },
      type: Object
    },
    type: {
      default: 'right',
      type: String
    }
  },
  emits: ['update:visible', 'selected'],

  setup(props, { emit }) {
    const translate = useLocale(cN);
    const classes = computed(() => {
      const prefixCls = 'nut-fixed-nav';
      return {
        [prefixCls]: true,
        active: props.visible,
        [props.type]: true
      };
    });

    const current = ref(-1);

    const updateValue = (value: boolean = !props.visible) => {
      emit('update:visible', value);
    };
    const selected = (item: any, event: Event) => {
      emit('selected', {
        item,
        event
      });
      current.value = item.id;
    };

    return { classes, updateValue, selected, translate, current };
  }
});
</script>
