// src/packages/input/index.vue
<template>
  <view :class="classes">
    <view class="nut-input-label">
      <view class="nut-input-require" v-if="requireShow">*</view>
      <view v-if="label" class="label-string">{{ label }}</view>
    </view>
    <input
      class="input-text"
      :style="styles"
      :type="type"
      :maxlength="maxLength"
      :placeholder="placeholder"
      :disabled="disabled"
      :readonly="readonly"
      :value="modelValue"
      @input="valueChange"
      @focus="valueFocus"
      @blur="valueBlur"
    />
    <view
      @click="handleClear"
      class="nut-textinput-clear"
      v-if="clearable && !readonly"
      v-show="active && modelValue.length > 0"
    >
      <nut-icon name="close-little" size="12px"></nut-icon>
    </view>
  </view>
</template>
<script lang="ts">
import { ref, computed } from 'vue';
import { createComponent } from '@/utils/create';
import { formatNumber } from './util';

const { componentName, create } = createComponent('input');
interface Events {
  eventName: 'change' | 'focus' | 'blur' | 'clear' | 'update:modelValue';
  params: (string | number | Event)[];
}
export default create({
  props: {
    type: {
      type: String,
      default: 'text'
    },
    modelValue: {
      type: [String, Number],
      default: ''
    },
    placeholder: {
      type: String,
      default: '请输入信息'
    },
    label: {
      type: String,
      default: ''
    },
    requireShow: {
      type: Boolean,
      default: false
    },
    disabled: {
      type: Boolean,
      default: false
    },
    readonly: {
      type: Boolean,
      default: false
    },
    textAlign: {
      type: String,
      default: 'left'
    },
    maxLength: {
      type: [String, Number],
      default: ''
    },
    clearable: {
      type: Boolean,
      default: true
    }
  },

  emits: ['change', 'update:modelValue', 'blur', 'focus', 'clear'],

  setup(props, { emit }) {
    const active = ref(false);

    const classes = computed(() => {
      const prefixCls = componentName;
      return {
        [prefixCls]: true,
        [`${prefixCls}-disabled`]: props.disabled
      };
    });

    const styles = computed(() => {
      return {
        textAlign: props.textAlign
      };
    });

    const valueChange = (event: Event) => {
      const input = event.target as HTMLInputElement;
      let val = input.value;

      if (props.maxLength && val.length > Number(props.maxLength)) {
        val = val.slice(0, Number(props.maxLength));
      }
      if (props.type === 'digit') {
        val = formatNumber(val, true);
      }
      if (props.type === 'number') {
        val = formatNumber(val, false);
      }
      emit('change', val, event);
      emit('update:modelValue', val, event);
    };

    const valueFocus = (event: Event) => {
      const input = event.target as HTMLInputElement;
      let value = input.value;
      active.value = true;
      emit('focus', value, event);
    };

    const valueBlur = (event: Event) => {
      setTimeout(() => {
        active.value = false;
      }, 0);

      const input = event.target as HTMLInputElement;
      let value = input.value;
      emit('blur', value, event);
    };

    const handleClear = (event: Event) => {
      emit('change', '', event);
      emit('update:modelValue', '', event);
    };

    return {
      active,
      classes,
      styles,
      valueChange,
      valueFocus,
      valueBlur,
      handleClear
    };
  }
});
</script>

<style lang="scss">
@import 'index.scss';
</style>

// src/packages/input/input.tsx
import React, { FunctionComponent, useEffect, useState } from 'react'
import './input.scss'
import bem from '@/utils/bem'
import { formatNumber } from './util'
import Icon from '../icon'

export interface InputProps {
  type: string
  defaultValue: any
  placeholder: string
  label: string
  requireShow: boolean
  disabled: boolean
  readonly: boolean
  textAlign: string
  maxLength: any
  clearable: boolean
  change?: (value: string | number, event: Event) => void
  blur?: (value: string | number, event: Event) => void
  focus?: (value: string | number, event: Event) => void
  clear?: (value: string | number, event: Event) => void
}
const defaultProps = {
  type: 'text',
  defaultValue: '',
  placeholder: '请输入信息',
  label: '',
  requireShow: false,
  disabled: false,
  readonly: false,
  textAlign: 'left',
  maxLength: '',
  clearable: true,
} as InputProps

export const Input: FunctionComponent<Partial<InputProps> & React.HTMLAttributes<HTMLDivElement>> =
  (props) => {
    const {
      type,
      defaultValue,
      placeholder,
      label,
      requireShow,
      disabled,
      readonly,
      textAlign,
      maxLength,
      clearable,
      change,
      blur,
      focus,
      clear,
    } = { ...defaultProps, ...props }

    const inputBem = bem('input')
    const [inputValue, SetInputValue] = useState('')
    const [active, SetActive] = useState(false)

    useEffect(() => {
      if (defaultValue) {
        SetInputValue(defaultValue)
      }
    }, [defaultValue])

    const valueChange = (event: Event) => {
      let val: any = (event.target as any).value
      if (maxLength && val.length > Number(maxLength)) {
        val = val.slice(0, Number(maxLength))
      }
      if (type === 'digit') {
        val = formatNumber(val, true)
      }
      if (type === 'number') {
        val = formatNumber(val, false)
      }
      if (change) {
        change(val, event)
      }
      SetInputValue(val)
    }

    const valueFocus = (event: Event) => {
      let val: any = (event.target as any).value
      SetActive(true)
      if (focus) {
        focus(val, event)
      }
    }

    const valueBlur = (event: Event) => {
      setTimeout(() => {
        SetActive(false)
      }, 0)
      let val: any = (event.target as any).value
      if (blur) {
        blur(val, event)
      }
    }
    const handleClear = (event: Event) => {
      if (clear) {
        clear('', event)
      }
      SetInputValue('')
    }

    return (
      <div className={`${inputBem()} ${disabled ? inputBem('disabled') : ''}`}>
        <div className={inputBem('label')}>
          {requireShow ? <div className={inputBem('require')}>*</div> : null}
          {label ? <div className="label-string">{label}</div> : null}
        </div>
        <input
          className="input-text"
          type={type}
          placeholder={placeholder}
          disabled={disabled}
          readOnly={readonly}
          value={inputValue}
          maxLength={maxLength}
          onBlur={valueBlur}
          onFocus={valueFocus}
          onChange={valueChange}
        />
        {clearable && !readonly ? (
          <div onClick={handleClear} className={inputBem('clear')}>
            {active && inputValue.length > 0 ? <Icon name="close-little" size="12px"></Icon> : null}
          </div>
        ) : null}
      </div>
    )
  }

Input.defaultProps = defaultProps
Input.displayName = 'NutInput'
