// src/packages/__VUE/inputnumber/input-number.vue
<template>
  <view :class="classes">
    <view
      class="nut-input-number__icon nut-input-number__left"
      :class="{ 'nut-input-number__icon--disabled': !reduceAllow() }"
      @click="reduce"
    >
      <slot name="left-icon">
        <Minus :width="pxCheck(buttonSize)" :height="pxCheck(buttonSize)" />
      </slot>
    </view>
    <input
      type="number"
      :min="min"
      :max="max"
      :style="{ width: pxCheck(inputWidth), height: pxCheck(buttonSize) }"
      :disabled="disabled"
      :readonly="readonly"
      :value="modelValue"
      @input="change"
      @blur="blur"
      @focus="focus"
    />
    <view
      class="nut-input-number__icon nut-input-number__right"
      :class="{ 'nut-input-number__icon--disabled': !addAllow() }"
      @click="add"
    >
      <slot name="right-icon">
        <Plus :width="pxCheck(buttonSize)" :height="pxCheck(buttonSize)" />
      </slot>
    </view>
  </view>
</template>
<script setup lang="ts">
import { computed, toRef, watch } from 'vue'
import { pxCheck } from '@/packages/utils/pxCheck'
import { Minus, Plus } from '@nutui/icons-vue'
import { useFormDisabled } from '../form/common'

defineOptions({
  name: 'NutInputNumber'
})

export type InputNumberProps = Partial<{
  modelValue: string | number
  inputWidth: string | number
  buttonSize: string | number
  min: string | number
  max: string | number
  step: string | number
  decimalPlaces: string | number
  disabled: boolean
  readonly: boolean
}>

const props = withDefaults(defineProps<InputNumberProps>(), {
  modelValue: 0,
  inputWidth: '',
  buttonSize: '',
  min: 1,
  max: 9999,
  step: 1,
  decimalPlaces: 0,
  disabled: false,
  readonly: false
})

const emit = defineEmits(['update:modelValue', 'change', 'blur', 'focus', 'reduce', 'add', 'overlimit'])

const disabled = useFormDisabled(toRef(props, 'disabled'))
const classes = computed(() => {
  const prefixCls = 'nut-input-number'
  return {
    [prefixCls]: true,
    [`${prefixCls}--disabled`]: disabled.value
  }
})
const fixedDecimalPlaces = (v: string | number): string => {
  return Number(v).toFixed(Number(props.decimalPlaces))
}
const change = (event: Event) => {
  const input = event.target as HTMLInputElement
  emit('update:modelValue', input.value, event)
  emit('change', input.value, event)
}
const emitChange = (value: string | number, event: Event) => {
  let output_value: number | string = fixedDecimalPlaces(value)
  emit('update:modelValue', output_value, event)
  if (Number(props.modelValue) !== Number(output_value)) emit('change', output_value, event)
}
const addAllow = (value = Number(props.modelValue)): boolean => {
  return value < Number(props.max) && !disabled.value
}
const reduceAllow = (value = Number(props.modelValue)): boolean => {
  return value > Number(props.min) && !disabled.value
}
const reduce = (event: Event) => {
  if (disabled.value) return
  emit('reduce', event)
  let output_value = Number(props.modelValue) - Number(props.step)
  if (reduceAllow() && output_value >= Number(props.min)) {
    emitChange(output_value, event)
  } else {
    emitChange(Number(props.min), event)
    emit('overlimit', event, 'reduce')
  }
}
const add = (event: Event) => {
  if (disabled.value) return
  emit('add', event)
  let output_value = Number(props.modelValue) + Number(props.step)
  if (addAllow() && output_value <= Number(props.max)) {
    emitChange(output_value, event)
  } else {
    emitChange(Number(props.max), event)
    emit('overlimit', event, 'add')
  }
}
const focus = (event: Event) => {
  if (disabled.value) return
  if (props.readonly) return
  emit('focus', event)
}
const blur = (event: Event) => {
  if (disabled.value) return
  if (props.readonly) return
  const input = event.target as HTMLInputElement
  let value = Number(input.value)
  if (value < Number(props.min)) {
    value = Number(props.min)
  } else if (value > Number(props.max)) {
    value = Number(props.max)
  }
  emitChange(value, event)
  emit('blur', event)
}
const format = (val: string | number) => {
  let value = Number(val)
  if (value < Number(props.min)) {
    value = Number(props.min)
  } else if (value > Number(props.max)) {
    value = Number(props.max)
  }
  return value
}
watch(
  () => [props.max, props.min],
  () => {
    if (Number(props.min) > Number(props.max)) {
      console.warn('[NutUI] <InputNumber>', 'props.max < props.min')
    }
    const value = format(props.modelValue)
    if (value !== Number(props.modelValue)) {
      emitChange(value, {} as Event)
    }
  }
)
</script>

// src/packages/inputnumber/inputnumber.tsx
import React, { useState, useEffect, FunctionComponent, ChangeEvent, FocusEvent } from 'react'
import Icon from '@/packages/icon'
import classNames from 'classnames'
import bem from '@/utils/bem'
import './inputnumber.scss'

export interface InputNumberProps {
  disabled: boolean
  buttonSize: string | number
  min: string | number
  max: string | number
  inputWidth: string | number
  readonly: boolean
  modelValue: string | number
  step: string | number
  decimalPlaces: string | number
  isAsync: boolean
  add: (e: MouseEvent) => void
  reduce: (e: MouseEvent) => void
  overlimit: (e: MouseEvent) => void
  blur: (e: ChangeEvent<HTMLInputElement>) => void
  focus: (e: FocusEvent<HTMLInputElement>) => void
  change: (param: string | number, e: MouseEvent | ChangeEvent<HTMLInputElement>) => void
}
const defaultProps = {
  disabled: false,
  buttonSize: '',
  min: 1,
  max: 9999,
  inputWidth: '',
  readonly: false,
  modelValue: 0,
  step: 1,
  decimalPlaces: 0,
  isAsync: false,
} as InputNumberProps
function pxCheck(value: string | number): string {
  return Number.isNaN(Number(value)) ? String(value) : `${value}px`
}
export const InputNumber: FunctionComponent<
  Partial<InputNumberProps> & React.HTMLAttributes<HTMLDivElement>
> = (props) => {
  const {
    children,
    disabled,
    buttonSize,
    min,
    max,
    inputWidth,
    readonly,
    modelValue,
    decimalPlaces,
    step,
    isAsync,
    add,
    reduce,
    change,
    overlimit,
    blur,
    focus,
  } = {
    ...defaultProps,
    ...props,
  }
  const [inputValue, setInputValue] = useState(modelValue)
  useEffect(() => {
    setInputValue(modelValue)
  }, [modelValue])

  const b = bem('inputnumber')

  const addAllow = (value = Number(inputValue)) => {
    return value < Number(max) && !disabled
  }

  const reduceAllow = (value = Number(inputValue)) => {
    return value > Number(min) && !disabled
  }

  const classes = classNames(b(''), {
    [`${b('')}--disabled`]: disabled,
  })

  const iconMinusClasses = classNames('nut-inputnumber__icon', {
    'nut-inputnumber__icon--disabled': !reduceAllow(),
  })

  const iconAddClasses = classNames('nut-inputnumber__icon', {
    'nut-inputnumber__icon--disabled': !addAllow(),
  })

  const fixedDecimalPlaces = (v: string | number): string => {
    return Number(v).toFixed(Number(decimalPlaces))
  }

  const emitChange = (value: string | number, e: MouseEvent | ChangeEvent<HTMLInputElement>) => {
    const output_value: number | string = fixedDecimalPlaces(value)
    change && change(output_value, e)
    if (!isAsync) {
      setInputValue(output_value)
    }
  }

  const reduceNumber = (e: MouseEvent) => {
    reduce && reduce(e)
    if (reduceAllow()) {
      let output_value = Number(inputValue) - Number(step)
      emitChange(output_value, e)
    } else {
      overlimit && overlimit(e)
    }
  }

  const addNumber = (e: MouseEvent) => {
    add && add(e)
    if (addAllow()) {
      const output_value = Number(inputValue) + Number(step)
      emitChange(output_value, e)
    } else {
      overlimit && overlimit(e)
    }
  }

  const changeValue = (e: ChangeEvent<HTMLInputElement>) => {
    const input = e.target as HTMLInputElement
    change && change(input.valueAsNumber, e)
    if (!isAsync) {
      if (Number.isNaN(input.valueAsNumber)) {
        setInputValue(inputValue)
      } else {
        setInputValue(input.valueAsNumber)
      }
    }
  }

  const focusValue = (e: FocusEvent<HTMLInputElement>) => {
    if (disabled) return
    if (readonly) return
    focus && focus(e)
  }

  const burValue = (e: ChangeEvent<HTMLInputElement>) => {
    if (disabled) return
    if (readonly) return
    const input = e.target as HTMLInputElement
    let value = input.valueAsNumber
    if (value < Number(min)) {
      value = Number(min)
    } else if (value > Number(max)) {
      value = Number(max)
    }
    emitChange(value, e)
    blur && blur(e)
  }
  return (
    <div className={classes} style={{ height: pxCheck(buttonSize) }}>
      <Icon className={iconMinusClasses} size={buttonSize} name="minus" click={reduceNumber} />
      <input
        type="number"
        min={min}
        max={max}
        style={{ width: pxCheck(inputWidth) }}
        disabled={disabled}
        readOnly={readonly}
        value={inputValue}
        onInput={changeValue}
        onBlur={burValue}
        onFocus={focusValue}
      />
      <Icon className={iconAddClasses} size={buttonSize} name="plus" click={addNumber} />
    </div>
  )
}

InputNumber.defaultProps = defaultProps
InputNumber.displayName = 'NutInputNumber'
