// src/packages/drag/drag.tsx
import React, { FunctionComponent, useState, useEffect, useRef } from 'react'
import './drag.scss'

export interface DragProps {
  attract: boolean
  direction: string
  boundary: {
    top: number
    left: number
    right: number
    bottom: number
  }
  style: any
}
const defaultProps = {
  attract: false,
  direction: 'all',
  boundary: {
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  style: {},
} as DragProps
export const Drag: FunctionComponent<Partial<DragProps> & React.HTMLAttributes<HTMLDivElement>> = (
  props
) => {
  const { attract, direction, boundary, style, children } = { ...defaultProps, ...props }
  const elWidth = useRef(0)
  const elHeight = useRef(0)
  const screenWidth = useRef(0)
  const screenHeight = useRef(0)
  const startTop = useRef(0)
  const startLeft = useRef(0)
  const nx = useRef(0)
  const ny = useRef(0)
  const xPum = useRef(0)
  const yPum = useRef(0)
  const position = useRef({
    x: 0,
    y: 0,
  })
  const boundaryState = useRef({
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  })
  const myDrag = useRef<HTMLDivElement>(null)
  const getInfo = () => {
    const el = myDrag.current
    if (el) {
      const domElem = document.documentElement
      elWidth.current = el.offsetWidth
      elHeight.current = el.offsetHeight
      screenWidth.current = domElem.clientWidth
      screenHeight.current = domElem.clientHeight
    }
  }

  const goLeft = (target: HTMLElement) => {
    if (boundary.left) {
      if (+target.style.left.split('px')[0] > boundary.left) {
        target.style.left = +target.style.left.split('px')[0] - 10 + 'px'
        window.requestAnimationFrame(() => {
          goLeft(target)
        })
      } else {
        target.style.left = `${boundary.left}px`
      }
    } else {
      if (+target.style.left.split('px')[0] > 10) {
        target.style.left = +target.style.left.split('px')[0] - 10 + 'px'
        window.requestAnimationFrame(() => {
          goLeft(target)
        })
      } else {
        target.style.left = '0px'
      }
    }
  }
  const goRight = (target: HTMLElement, rightLocation: number) => {
    if (rightLocation - parseInt(target.style.left.split('px')[0]) > 10) {
      target.style.left = parseInt(target.style.left.split('px')[0]) + 10 + 'px'
      window.requestAnimationFrame(() => {
        goRight(target, rightLocation)
      })
    } else {
      target.style.left = rightLocation + 'px'
    }
  }
  const touchMove = (e: TouchEvent) => {
    e.preventDefault()
    const target = e.currentTarget as HTMLElement
    if (e.targetTouches.length === 1) {
      const touch = e.targetTouches[0]
      const x = touch.clientX - position.current.x
      const y = touch.clientY - position.current.y
      xPum.current = startLeft.current + x
      yPum.current = startTop.current + y
      const rightLocation = screenWidth.current - elWidth.current - boundary.right
      if (Math.abs(xPum.current) > rightLocation) {
        xPum.current = rightLocation
      } else if (xPum.current <= boundary.left) {
        xPum.current = boundary.left
      }
      if (yPum.current < boundary.top) {
        yPum.current = boundary.top
      } else if (yPum.current > screenHeight.current - elHeight.current - boundary.bottom) {
        yPum.current = screenHeight.current - elHeight.current - boundary.bottom
      }
      if (props.direction != 'y') {
        target.style.left = `${xPum.current}px`
      }
      if (props.direction != 'x') {
        target.style.top = `${yPum.current}px`
      }
    }
  }
  const touchEnd = (e: TouchEvent) => {
    const target = e.currentTarget as HTMLElement
    const touch = e.changedTouches[0]
    let currX = touch.clientX
    const rightLocation = screenWidth.current - elWidth.current - boundary.right
    if (currX > rightLocation) {
      currX = rightLocation
    } else if (currX < boundary.left) {
      currX = boundary.left
    } else {
      currX = currX < screenWidth.current / 2 ? boundary.left : rightLocation
    }
    if (props.direction != 'y' && props.attract) {
      if (currX < screenWidth.current / 2) {
        window.requestAnimationFrame(() => {
          goLeft(target)
        })
      } else {
        window.requestAnimationFrame(() => {
          goRight(target, rightLocation)
        })
      }
    }
    if (props.direction !== 'x') {
      target.style.top = `${yPum.current}px`
    }
  }
  const touchStart = (e: React.TouchEvent<HTMLDivElement>) => {
    const target = e.currentTarget as HTMLElement
    const touches = e.touches[0]
    startTop.current = target.offsetTop
    startLeft.current = target.offsetLeft
    position.current = { x: touches.clientX, y: touches.clientY }

    target.removeEventListener('touchmove', touchMove, false)
    target.removeEventListener('touchend', touchEnd, false)
    target.addEventListener('touchmove', touchMove, false)
    target.addEventListener('touchend', touchEnd, false)
  }

  useEffect(() => {
    getInfo()
  }, [])

  return (
    <div
      className="nut-drag"
      style={style}
      ref={myDrag}
      onTouchStart={(event) => touchStart(event)}
    >
      {children}
    </div>
  )
}

Drag.defaultProps = defaultProps
Drag.displayName = 'NutDrag'

// src/packages/drag/drag.vue
<template>
  <div class="nut-drag" @touchstart="touchStart($event)">
    <slot></slot>
  </div>
</template>
<script>
import requestAniFrame from '../../utils/raf.js';
/**
 * @module drag
 * @description 拖拽组件，用于页面中需要拖拽的元素
 * @vue-prop {Boolean} [attract=false] - 拖拽元素是否需要自动吸边
 * @vue-prop {String} [direction='all'] - 拖拽元素的拖拽方向
 * @vue-prop {Number | String} [zIndex=11] - 拖拽元素的堆叠顺序
 * @vue-prop {Object} [boundary={top: 0,left: 0,right: 0,bottom: 0}] - 拖拽元素的拖拽边界
 * @vue-data {Number} elWidth 拖拽元素的宽度
 * @vue-data {Number} elHeight 拖拽元素的高度
 * @vue-data {Number} screenWidth 屏幕的宽度
 * @vue-data {Number} screenHeight 屏幕的高度
 * @vue-data {Number} startTop 拖拽元素距离顶部的距离
 * @vue-data {Number} startLeft 拖拽元素距离左侧的距离
 * @vue-data {Object} position 鼠标点击的位置，包含距离x轴和y轴的距离
 */
export default {
  name: 'nut-drag',
  props: {
    attract: {
      type: Boolean,
      default: false
    },
    direction: {
      type: String,
      default: 'all'
    },
    zIndex: {
      type: [Number, String],
      default: 11
    },
    boundary: {
      type: Object,
      default: function() {
        return {
          top: 0,
          left: 0,
          right: 0,
          bottom: 0
        };
      }
    }
  },
  data() {
    return {
      elWidth: 0,
      elHeight: 0,
      screenWidth: 0,
      screenHeight: 0,
      startTop: 0,
      startLeft: 0,
      position: { x: 0, y: 0 }
    };
  },
  methods: {
    /**
     * 获取拖拽元素的属性和屏幕的宽高，初始化拖拽元素的位置
     */
    getElementInfo() {
      const el = this.$el;
      const domElem = document.documentElement;
      this.elWidth = el.offsetWidth;
      this.elHeight = el.offsetHeight;
      this.screenWidth = domElem.clientWidth;
      this.screenHeight = domElem.clientHeight;
      el.style.zIndex = this.zIndex;
      if (this.boundary.left && el.style.left === 0) {
        el.style.left = this.boundary.left + 'px';
      } else if (this.boundary.right && el.style.right === 0) {
        el.style.right = this.boundary.right + 'px';
      }
      if (this.boundary.top && el.style.top === 0) {
        el.style.top = this.boundary.top + 'px';
      } else if (this.boundary.bottom && el.style.bottom === 0) {
        el.style.bottom = this.boundary.bottom + 'px';
      }
    },
    touchStart(e) {
      const target = e.currentTarget;
      this.startTop = target.offsetTop; // 元素距离顶部的距离
      this.startLeft = target.offsetLeft; // 元素距离左侧的距离
      this.position.x = e.touches[0].clientX; // 鼠标点击的x轴的距离
      this.position.y = e.touches[0].clientY; // 鼠标点击的y轴的距离
      this.$el.addEventListener('touchmove', this.touchMove, false);
      this.$el.addEventListener('touchend', this.touchEnd, false);
    },
    touchMove(e) {
      e.preventDefault();
      const target = e.currentTarget;
      if (e.targetTouches.length == 1) {
        const touch = e.targetTouches[0];
        this.nx = touch.clientX - this.position.x;
        this.ny = touch.clientY - this.position.y;
        this.xPum = this.startLeft + this.nx;
        this.yPum = this.startTop + this.ny;
        const rightLocation = this.screenWidth - this.elWidth - this.boundary.right;
        // 限制左右拖拽边界
        if (Math.abs(this.xPum) > rightLocation) {
          this.xPum = rightLocation;
        } else if (this.xPum <= this.boundary.left) {
          this.xPum = this.boundary.left;
        }
        // 限制上下拖拽边界
        if (this.yPum < this.boundary.top) {
          this.yPum = this.boundary.top;
        } else if (this.yPum > this.screenHeight - this.elHeight - this.boundary.bottom) {
          this.yPum = this.screenHeight - this.elHeight - this.boundary.bottom;
        }
        if (this.direction != 'y') {
          target.style.left = this.xPum + 'px';
        }
        if (this.direction != 'x') {
          target.style.top = this.yPum + 'px';
        }
      }
    },
    touchEnd(e) {
      const target = e.currentTarget;
      const touch = e.changedTouches[0];
      let currX = touch.clientX;
      const rightLocation = this.screenWidth - this.elWidth - this.boundary.right;
      if (currX > rightLocation) {
        currX = rightLocation;
        // console.log('往右划出边界');
      } else if (currX < this.boundary.left) {
        currX = this.boundary.left;
        // console.log('往左划出边界');
      } else {
        currX = currX < this.screenWidth / 2 ? this.boundary.left : rightLocation;
        // console.log('在边界内滑动');
      }
      if (this.direction != 'y' && this.attract) {
        if (currX < this.screenWidth / 2) {
          this.goLeft(target);
        } else {
          this.goRight(target, rightLocation);
        }
      }
      if (this.direction != 'x') {
        target.style.top = this.yPum + 'px';
      }
    },
    goLeft(target) {
      if (this.boundary.left) {
        if (target.style.left.split('px')[0] > this.boundary.left) {
          target.style.left = target.style.left.split('px')[0] - 10 + 'px';
          requestAniFrame(() => {
            this.goLeft(target);
          });
        } else {
          target.style.left = `${this.boundary.left}px`;
        }
      } else {
        if (target.style.left.split('px')[0] > 10) {
          target.style.left = target.style.left.split('px')[0] - 10 + 'px';
          requestAniFrame(() => {
            this.goLeft(target);
          });
        } else {
          target.style.left = '0px';
        }
      }
    },
    goRight(target, rightLocation) {
      if (rightLocation - parseInt(target.style.left.split('px')[0]) > 10) {
        target.style.left = parseInt(target.style.left.split('px')[0]) + 10 + 'px';
        requestAniFrame(() => {
          this.goRight(target, rightLocation);
        });
      } else {
        target.style.left = rightLocation + 'px';
      }
    }
  },
  mounted() {
    this.getElementInfo();
  },
  activated() {
    if (this.keepAlive) {
      this.keepAlive = false;
    }
  },
  deactivated() {
    this.keepAlive = true;
    this.$el.removeEventListener('touchmove', this.handleScroll, false);
    this.$el.removeEventListener('touchend', this.handleScroll, false);
  },
  destroyed() {
    this.$el.removeEventListener('touchmove', this.handleScroll, false);
    this.$el.removeEventListener('touchend', this.handleScroll, false);
  }
};
</script>
