// src/packages/drag/index.vue
<template>
  <view
    :class="classes"
    ref="myDrag"
    @touchstart="touchStart($event)"
    @touchmove="touchMove($event)"
    @touchend="touchEnd($event)"
  >
    <slot></slot>
  </view>
</template>

<script lang="ts">
import { onMounted, reactive, ref, computed } from 'vue';
import { createComponent } from '@/utils/create';
import requestAniFrame from '@/utils/raf';
const { componentName, create } = createComponent('drag');
export default create({
  props: {
    attract: {
      type: Boolean,
      default: false
    },
    direction: {
      type: String,
      default: 'all'
    },
    boundary: {
      type: Object,
      default: () => {
        return {
          top: 0,
          left: 0,
          right: 0,
          bottom: 0
        };
      }
    }
  },
  setup(props, { emit }) {
    const myDrag = ref();
    const state = reactive({
      elWidth: 0,
      elHeight: 0,
      screenWidth: 0,
      screenHeight: 0,
      startTop: 0,
      startLeft: 0,
      nx: 0,
      ny: 0,
      xPum: 0,
      yPum: 0,
      position: { x: 0, y: 0 },
      boundary: {
        top: 0,
        left: 0,
        right: 0,
        bottom: 0
      } as Record<string, any>
    });

    const classes = computed(() => {
      const prefixCls = componentName;
      return {
        [prefixCls]: true
      };
    });

    function getInfo() {
      const domElem = document.documentElement;
      state.elWidth = myDrag.value.offsetWidth;
      state.elHeight = myDrag.value.offsetHeight;
      state.screenWidth = domElem.clientWidth;
      state.screenHeight = domElem.clientHeight;
    }

    function goLeft(target: HTMLElement) {
      if (state.boundary.left) {
        if (+target.style.left.split('px')[0] > state.boundary.left) {
          target.style.left = +target.style.left.split('px')[0] - 10 + 'px';
          requestAniFrame(() => {
            goLeft(target);
          });
        } else {
          target.style.left = `${state.boundary.left}px`;
        }
      } else {
        if (+target.style.left.split('px')[0] > 10) {
          target.style.left = +target.style.left.split('px')[0] - 10 + 'px';
          requestAniFrame(() => {
            goLeft(target);
          });
        } else {
          target.style.left = '0px';
        }
      }
    }
    function goRight(target: HTMLElement, rightLocation: number) {
      if (rightLocation - parseInt(target.style.left.split('px')[0]) > 10) {
        target.style.left =
          parseInt(target.style.left.split('px')[0]) + 10 + 'px';
        requestAniFrame(() => {
          goRight(target, rightLocation);
        });
      } else {
        target.style.left = rightLocation + 'px';
      }
    }
    function touchMove(e: TouchEvent) {
      e.preventDefault();
      const target = e.currentTarget as HTMLElement;
      if (e.targetTouches.length === 1) {
        const touch = e.targetTouches[0];
        state.nx = touch.clientX - state.position.x;
        state.ny = touch.clientY - state.position.y;
        state.xPum = state.startLeft + state.nx;
        state.yPum = state.startTop + state.ny;
        const rightLocation =
          state.screenWidth - state.elWidth - state.boundary.right;
        if (Math.abs(state.xPum) > rightLocation) {
          state.xPum = rightLocation;
        } else if (state.xPum <= state.boundary.left) {
          state.xPum = state.boundary.left;
        }
        if (state.yPum < state.boundary.top) {
          state.yPum = state.boundary.top;
        } else if (
          state.yPum >
          state.screenHeight - state.elHeight - state.boundary.bottom
        ) {
          state.yPum =
            state.screenHeight - state.elHeight - state.boundary.bottom;
        }
        if (props.direction != 'y') {
          target.style.left = state.xPum + 'px';
        }
        if (props.direction != 'x') {
          target.style.top = state.yPum + 'px';
        }
      }
    }
    function touchEnd(e: TouchEvent) {
      const target = e.currentTarget as HTMLElement;
      const touch = e.changedTouches[0];
      let currX = touch.clientX;
      const rightLocation =
        state.screenWidth - state.elWidth - state.boundary.right;
      if (currX > rightLocation) {
        currX = rightLocation;
      } else if (currX < state.boundary.left) {
        currX = state.boundary.left;
      } else {
        currX =
          currX < state.screenWidth / 2 ? state.boundary.left : rightLocation;
      }
      if (props.direction !== 'y' && props.attract) {
        if (currX < state.screenWidth / 2) {
          requestAniFrame(() => {
            goLeft(target);
          });
        } else {
          requestAniFrame(() => {
            goRight(target, rightLocation);
          });
        }
      }
      if (props.direction !== 'x') {
        target.style.top = state.yPum + 'px';
      }
    }

    function touchStart(e: TouchEvent) {
      const target = e.currentTarget as HTMLElement;
      const touches = e.touches[0];
      state.startTop = target.offsetTop;
      state.startLeft = target.offsetLeft;
      state.position.x = touches.clientX;
      state.position.y = touches.clientY;
    }
    onMounted(() => {
      getInfo();
      state.boundary = props.boundary;
    });
    return {
      classes,
      myDrag,
      touchStart,
      touchMove,
      touchEnd
    };
  }
});
</script>

<style lang="scss">
@import 'index.scss';
</style>

// src/packages/drag/drag.tsx
import React, { FunctionComponent, useState, useEffect, useRef } from 'react'
import './drag.scss'

export interface DragProps {
  attract: boolean
  direction: string
  boundary: {
    top: number
    left: number
    right: number
    bottom: number
  }
  style: any
}
const defaultProps = {
  attract: false,
  direction: 'all',
  boundary: {
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  style: {},
} as DragProps
export const Drag: FunctionComponent<Partial<DragProps> & React.HTMLAttributes<HTMLDivElement>> = (
  props
) => {
  const { attract, direction, boundary, style, children } = { ...defaultProps, ...props }
  const elWidth = useRef(0)
  const elHeight = useRef(0)
  const screenWidth = useRef(0)
  const screenHeight = useRef(0)
  const startTop = useRef(0)
  const startLeft = useRef(0)
  const nx = useRef(0)
  const ny = useRef(0)
  const xPum = useRef(0)
  const yPum = useRef(0)
  const position = useRef({
    x: 0,
    y: 0,
  })
  const boundaryState = useRef({
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  })
  const myDrag = useRef<HTMLDivElement>(null)
  const getInfo = () => {
    const el = myDrag.current
    if (el) {
      const domElem = document.documentElement
      elWidth.current = el.offsetWidth
      elHeight.current = el.offsetHeight
      screenWidth.current = domElem.clientWidth
      screenHeight.current = domElem.clientHeight
    }
  }

  const goLeft = (target: HTMLElement) => {
    if (boundary.left) {
      if (+target.style.left.split('px')[0] > boundary.left) {
        target.style.left = +target.style.left.split('px')[0] - 10 + 'px'
        window.requestAnimationFrame(() => {
          goLeft(target)
        })
      } else {
        target.style.left = `${boundary.left}px`
      }
    } else {
      if (+target.style.left.split('px')[0] > 10) {
        target.style.left = +target.style.left.split('px')[0] - 10 + 'px'
        window.requestAnimationFrame(() => {
          goLeft(target)
        })
      } else {
        target.style.left = '0px'
      }
    }
  }
  const goRight = (target: HTMLElement, rightLocation: number) => {
    if (rightLocation - parseInt(target.style.left.split('px')[0]) > 10) {
      target.style.left = parseInt(target.style.left.split('px')[0]) + 10 + 'px'
      window.requestAnimationFrame(() => {
        goRight(target, rightLocation)
      })
    } else {
      target.style.left = rightLocation + 'px'
    }
  }
  const touchMove = (e: TouchEvent) => {
    e.preventDefault()
    const target = e.currentTarget as HTMLElement
    if (e.targetTouches.length === 1) {
      const touch = e.targetTouches[0]
      const x = touch.clientX - position.current.x
      const y = touch.clientY - position.current.y
      xPum.current = startLeft.current + x
      yPum.current = startTop.current + y
      const rightLocation = screenWidth.current - elWidth.current - boundary.right
      if (Math.abs(xPum.current) > rightLocation) {
        xPum.current = rightLocation
      } else if (xPum.current <= boundary.left) {
        xPum.current = boundary.left
      }
      if (yPum.current < boundary.top) {
        yPum.current = boundary.top
      } else if (yPum.current > screenHeight.current - elHeight.current - boundary.bottom) {
        yPum.current = screenHeight.current - elHeight.current - boundary.bottom
      }
      if (props.direction != 'y') {
        target.style.left = `${xPum.current}px`
      }
      if (props.direction != 'x') {
        target.style.top = `${yPum.current}px`
      }
    }
  }
  const touchEnd = (e: TouchEvent) => {
    const target = e.currentTarget as HTMLElement
    const touch = e.changedTouches[0]
    let currX = touch.clientX
    const rightLocation = screenWidth.current - elWidth.current - boundary.right
    if (currX > rightLocation) {
      currX = rightLocation
    } else if (currX < boundary.left) {
      currX = boundary.left
    } else {
      currX = currX < screenWidth.current / 2 ? boundary.left : rightLocation
    }
    if (props.direction != 'y' && props.attract) {
      if (currX < screenWidth.current / 2) {
        window.requestAnimationFrame(() => {
          goLeft(target)
        })
      } else {
        window.requestAnimationFrame(() => {
          goRight(target, rightLocation)
        })
      }
    }
    if (props.direction !== 'x') {
      target.style.top = `${yPum.current}px`
    }
  }
  const touchStart = (e: React.TouchEvent<HTMLDivElement>) => {
    const target = e.currentTarget as HTMLElement
    const touches = e.touches[0]
    startTop.current = target.offsetTop
    startLeft.current = target.offsetLeft
    position.current = { x: touches.clientX, y: touches.clientY }

    target.removeEventListener('touchmove', touchMove, false)
    target.removeEventListener('touchend', touchEnd, false)
    target.addEventListener('touchmove', touchMove, false)
    target.addEventListener('touchend', touchEnd, false)
  }

  useEffect(() => {
    getInfo()
  }, [])

  return (
    <div
      className="nut-drag"
      style={style}
      ref={myDrag}
      onTouchStart={(event) => touchStart(event)}
    >
      {children}
    </div>
  )
}

Drag.defaultProps = defaultProps
Drag.displayName = 'NutDrag'
