// src/packages/cell/cell.tsx
import React, { FunctionComponent, CSSProperties, ReactNode } from 'react'
import { useHistory } from 'react-router-dom'
import './cell.scss'
import bem from '@/utils/bem'
import { Icon } from '../icon/icon'

export interface CellProps {
  title: string
  subTitle: string
  desc: string
  descTextAlign: string
  isLink: boolean
  to: string
  replace: boolean
  url: string
  icon: string
  classPrefix: string
  extra: ReactNode
  click: (event: React.MouseEvent<HTMLDivElement, MouseEvent>) => void
}
const defaultProps = {
  title: '',
  subTitle: '',
  desc: '',
  descTextAlign: 'right',
  isLink: false,
  to: '',
  replace: false,
  url: '',
  icon: '',
  classPrefix: 'nutui-cell',
  extra: '',
  click: (event: React.MouseEvent<HTMLDivElement, MouseEvent>) => {},
} as CellProps
export const Cell: FunctionComponent<Partial<CellProps>> = (props) => {
  const {
    children,
    click,
    isLink,
    to,
    url,
    replace,
    classPrefix,
    descTextAlign,
    desc,
    icon,
    title,
    subTitle,
    extra,
  } = {
    ...defaultProps,
    ...props,
  }
  const b = bem('cell')
  let history = useHistory()
  const handleClick = (event: React.MouseEvent<HTMLDivElement, MouseEvent>) => {
    click(event)
    if (to && history) {
      history[replace ? 'replace' : 'push'](to)
    } else if (url) {
      replace ? location.replace(url) : (location.href = url)
    }
  }

  const styles = {
    textAlign: descTextAlign,
  }
  return (
    <div
      className={`${b({ clickable: isLink || to ? true : false }, [classPrefix])} `}
      onClick={(event) => handleClick(event)}
    >
      {children ? (
        children
      ) : (
        <>
          {title || subTitle || icon ? (
            <>
              {icon ? (
                <div className={`${b('icon')}`}>
                  <Icon name={icon} />
                </div>
              ) : null}
              <div className={`${b('title', { icon: icon ? true : false })}`}>
                {subTitle ? (
                  <>
                    <div className={b('maintitle')}>{title}</div>
                    <div className={b('subtitle')}>{subTitle}</div>
                  </>
                ) : (
                  <>{title}</>
                )}
              </div>
            </>
          ) : null}
          {desc ? (
            <div className={b('desc')} style={styles as CSSProperties}>
              {desc}
            </div>
          ) : null}
        </>
      )}
      {extra ? extra : null}
      {!extra && (isLink || to) ? (
        <div className={b('link')}>
          <Icon name="right"></Icon>
        </div>
      ) : null}
    </div>
  )
}

Cell.defaultProps = defaultProps
Cell.displayName = 'NutCell'

// src/packages/__VUE/cell/index.vue
<template>
  <view :class="classes" @click="handleClick">
    <slot>
      <view
        class="nut-cell__title"
        :class="{ icon: icon }"
        v-if="title || subTitle || icon"
      >
        <nut-icon v-if="icon" class="icon" :name="icon"></nut-icon>
        <template v-if="subTitle">
          <view class="title">{{ title }}</view>
          <view class="nut-cell__title-desc">{{ subTitle }}</view>
        </template>
        <template v-else>
          {{ title }}
        </template>
      </view>
      <view
        v-if="desc"
        class="nut-cell__value"
        :style="{ 'text-align': descTextAlign }"
        >{{ desc }}</view
      >

      <slot v-if="$slots.link" name="link"></slot>
      <nut-icon
        v-else-if="isLink || to"
        class="nut-cell__link"
        name="right"
      ></nut-icon>
    </slot>
  </view>
</template>

<script lang="ts">
import { computed } from 'vue';
import { createComponent } from '@/packages/utils/create';
import { useRouter } from 'vue-router';
import CellGroup from '@/packages/__VUE/cellgroup/index.vue';
const { componentName, create } = createComponent('cell');
export default create({
  props: {
    title: { type: String, default: '' },
    subTitle: { type: String, default: '' },
    desc: { type: String, default: '' },
    descTextAlign: { type: String, default: 'right' },
    isLink: { type: Boolean, default: false },
    to: { type: String, default: '' },
    replace: { type: Boolean, default: false },
    url: { type: String, default: '' },
    icon: { type: String, default: '' }
  },
  emits: ['click'],
  children: [CellGroup],
  components: {
    [CellGroup.name]: CellGroup
  },
  setup(props, { emit }) {
    const classes = computed(() => {
      const prefixCls = componentName;
      return {
        [prefixCls]: true,
        [`${prefixCls}--clickable`]: props.isLink || props.to
      };
    });
    const router = useRouter();
    const handleClick = (event: Event) => {
      emit('click', event);
      if (props.to && router) {
        router[props.replace ? 'replace' : 'push'](props.to);
      } else if (props.url) {
        props.replace
          ? location.replace(props.url)
          : (location.href = props.url);
      }
    };

    return {
      handleClick,
      classes
    };
  }
});
</script>

<style lang="scss">
@import 'index.scss';
</style>
