// src/packages/rate/rate.tsx
import React, { FunctionComponent, useEffect, useState } from 'react'
import './rate.scss'
import bem from '@/utils/bem'
import Icon from '../icon'

export interface RateProps {
  count: string | number
  modelValue: string | number
  iconSize: string | number
  activeColor: string
  voidColor: string
  checkedIcon: string
  uncheckedIcon: string
  disabled: boolean
  readonly: boolean
  allowHalf: boolean
  spacing: string | number
  change: (val: number) => void
}
const defaultProps = {
  count: 5,
  modelValue: 0,
  iconSize: 18,
  activeColor: '',
  voidColor: '',
  checkedIcon: 'star-fill-n',
  uncheckedIcon: 'star-n',
  disabled: false,
  readonly: false,
  allowHalf: false,
  spacing: 14,
} as RateProps
export const Rate: FunctionComponent<Partial<RateProps>> = (props) => {
  const {
    count,
    modelValue,
    iconSize,
    activeColor,
    voidColor,
    checkedIcon,
    uncheckedIcon,
    disabled,
    readonly,
    allowHalf,
    spacing,
    change,
  } = { ...defaultProps, ...props }
  const b = bem('rate')
  const bi = bem('rate-item')

  const [countArray, setCountArray] = useState([1, 2, 3, 4, 5])
  const [score, setScore] = useState(0)

  useEffect(() => {
    const tmp = []
    for (let i = 1; i <= Number(count); i++) {
      tmp.push(i)
    }
    setCountArray(tmp)
  }, [count])

  useEffect(() => {
    setScore(Number(modelValue))
  }, [modelValue])

  const pxCheck = (value: string | number): string => {
    return isNaN(Number(value)) ? String(value) : `${value}px`
  }

  const onClick = (e: React.MouseEvent, index: number) => {
    e.preventDefault()
    e.stopPropagation()
    if (disabled || readonly) return
    let value = 0
    if (index === 1 && score === index) {
    } else {
      value = index
      if (allowHalf) {
        if ((e?.target as Element).className.includes('__icon--half')) {
          value -= 0.5
        }
      }
    }
    setScore(value)

    change && change(value)
  }
  return (
    <div className={b()}>
      {countArray.map((n) => {
        return (
          <div
            className={bi()}
            key={n}
            onClick={(event) => onClick(event, n)}
            style={{ marginRight: pxCheck(spacing) }}
          >
            <Icon
              size={iconSize}
              className={`${bi('icon')} ${disabled || n > score ? bi('icon--disabled') : ''}`}
              name={n <= score ? checkedIcon : uncheckedIcon}
              color={n <= score ? activeColor : voidColor}
            />
            {allowHalf && score > n - 1 && (
              <Icon
                className={`${bi('icon')} ${bi('icon--half')}`}
                color={n <= score ? activeColor : voidColor}
                size={iconSize}
                name={checkedIcon}
              />
            )}
            {allowHalf && score < n - 1 && (
              <Icon
                className={`${bi('icon')} ${bi('icon--disabled')} ${bi('icon--half')}`}
                color={voidColor}
                size={iconSize}
                name={uncheckedIcon}
              />
            )}
          </div>
        )
      })}
    </div>
  )
}

Rate.defaultProps = defaultProps
Rate.displayName = 'NutRate'

// src/packages/__VUE/rate/rate.vue
<template>
  <view class="nut-rate" @touchstart="onTouchStart" @touchmove="onTouchMove">
    <view
      v-for="n in Number(count)"
      :id="'rateRefs-' + refRandomId + n"
      :key="n"
      ref="rateRefs"
      class="nut-rate-item"
      :style="n < Number(count) ? { marginRight: pxCheck(spacing) } : {}"
    >
      <view class="nut-rate-item__icon--full">
        <component
          :is="
            renderIcon(customIcon, {
              width: size,
              height: size,
              size,
              color: n <= Number(modelValue) ? activeColor : voidColor
            })
          "
          class="nut-rate-item__icon"
          :class="{ 'nut-rate-item__icon--disabled': disabled || n > Number(modelValue) }"
          @click="onClick(1, n)"
        ></component>
      </view>
      <view v-if="allowHalf && Number(modelValue) + 1 > n" class="nut-rate-item__icon--half">
        <component
          :is="
            renderIcon(customIcon, {
              width: size,
              height: size,
              size,
              color: n <= Number(modelValue) + 1 ? activeColor : voidColor
            })
          "
          class="nut-rate-item__icon"
          @click="onClick(2, n)"
        ></component>
      </view>
      <view v-else-if="allowHalf && Number(modelValue) + 1 < n" class="nut-rate-item__icon--half">
        <component
          :is="renderIcon(customIcon, { width: size, height: size, size, color: voidColor })"
          class="nut-rate-item__icon nut-rate-item__icon--disabled"
          @click="onClick(2, n)"
        ></component>
      </view>
    </view>
  </view>
</template>
<script setup lang="ts">
import { Ref, ref, toRef } from 'vue';
import { StarFillN } from '@nutui/icons-vue';
import { renderIcon } from '@/packages/utils/create';
import { pxCheck } from '@/packages/utils/pxCheck';
import { useTouch } from '@/packages/utils/useTouch';
import { useFormDisabled } from '../form/common';

defineOptions({
  name: 'NutRate'
});

export type RateProps = Partial<{
  count: string | number;
  modelValue: string | number;
  customIcon: any;
  size: string | number;
  activeColor: string;
  voidColor: string;
  readonly: boolean;
  disabled: boolean;
  allowHalf: boolean;
  touchable: boolean;
  spacing: string | number;
}>;

const props = withDefaults(defineProps<RateProps>(), {
  count: 5,
  modelValue: 0,
  customIcon: () => StarFillN,
  activeColor: '',
  voidColor: '',
  readonly: false,
  disabled: false,
  allowHalf: false,
  touchable: true
});

const emit = defineEmits(['update:modelValue', 'change']);

const refRandomId = Math.random().toString(36).slice(-8);
const disabled = useFormDisabled(toRef(props, 'disabled'));
const rateRefs = ref<HTMLElement[]>([]);
const updateVal = (value: number) => {
  emit('update:modelValue', value);
  emit('change', value);
};
const onClick = (e: number, index: number) => {
  if (disabled.value || props.readonly) return;
  let value = 0;
  if (index === 1 && props.modelValue === index) {
    value = 0;
  } else {
    value = index;
    if (props.allowHalf && e == 2) {
      value -= 0.5;
    }
  }
  updateVal(value);
};
const getScoreByPosition = (x: number, rateRefs: Ref<HTMLElement[]>, allowHalf: boolean) => {
  let v = 0;
  for (let index = rateRefs.value.length - 1; index >= 0; index--) {
    const item = rateRefs.value[index];
    if (x > item.offsetLeft) {
      if (allowHalf) {
        v = index + (x > item.offsetLeft + item.clientWidth / 2 ? 1 : 0.5);
      } else {
        v = index + 1;
      }
      break;
    }
  }
  return v;
};
const touch = useTouch();
const onTouchStart = (event: TouchEvent) => {
  if (!props.touchable || props.readonly) return;
  touch.start(event);
};
const onTouchMove = (event: TouchEvent) => {
  if (!props.touchable) return;
  touch.move(event);
  if (touch.isHorizontal()) {
    if (rateRefs.value) {
      event.preventDefault();
      updateVal(getScoreByPosition(touch.moveX.value, rateRefs, props.allowHalf));
    }
  }
};
</script>
