// src/packages/avatar/avatar.tsx
import React, { FunctionComponent, MouseEventHandler } from 'react'
import Icon from '@/packages/icon'
import classNames from 'classnames'
import './avatar.scss'

export interface AvatarProps {
  size: string
  icon: string
  shape: string
  bgColor: string
  prefixCls: string
  src: string
}
const defaultProps: AvatarProps = {
  size: 'normal',
  icon: '',
  shape: 'round',
  bgColor: '#eee',
  prefixCls: 'nut-avatar',
  src: '',
}
export const Avatar: FunctionComponent<
  Partial<AvatarProps> & React.HTMLAttributes<HTMLDivElement>
> = (props) => {
  const { children, prefixCls, size, shape, bgColor, src, icon, className, ...rest } = {
    ...defaultProps,
    ...props,
  }
  const sizeValue = ['large', 'normal', 'small']
  const classes = classNames({
    [`${prefixCls}`]: true,
    ['avatar-' + size]: true,
    ['avatar-' + shape]: true,
  })
  const cls = classNames(classes, className)
  const styles: React.CSSProperties = {
    width: sizeValue.indexOf(size) > -1 ? '' : `${size}px`,
    height: sizeValue.indexOf(size) > -1 ? '' : `${size}px`,
    backgroundImage: src ? `url(${src})` : '',
    backgroundColor: `${bgColor}`,
  }
  const iconStyles = !!icon && !src ? icon : ''
  const handleClick: MouseEventHandler<HTMLDivElement> = (e) => {
    if (props.onClick) {
      props.onClick(e)
    }
  }
  return (
    <div className={cls} {...rest} style={styles} onClick={handleClick}>
      <Icon className="icon" name={iconStyles} />
      {children && <span className="text">{children}</span>}
    </div>
  )
}

Avatar.defaultProps = defaultProps
Avatar.displayName = 'NutAvatar'

// src/packages/avatar/index.vue
<template>
  <view :style="styles" :class="classes" @click="activeAvatar">
    <nut-icon class="icon" :name="iconStyles"></nut-icon>
    <view class="text" v-if="isShowText">
      <slot></slot>
    </view>
  </view>
</template>
<script lang="ts">
import { toRefs, computed } from 'vue';
import { createComponent } from '@/utils/create';
const { componentName, create } = createComponent('avatar');
import Icon from '@/packages/icon/index.vue';
export default create({
  children: [Icon],
  props: {
    size: {
      type: String,
      default: 'normal'
    },
    shape: {
      type: String,
      default: 'round'
    },
    bgColor: {
      type: String,
      default: '#eee'
    },
    bgIcon: {
      type: String,
      default: ''
    },
    bgImage: {
      type: String,
      default: ''
    }
  },
  emits: ['active-avatar'],
  setup(props, { emit, slots }) {
    const { size, shape, bgColor, bgIcon, bgImage } = toRefs(props);
    const sizeValue = ['large', 'middle', 'small'];
    const classes = computed(() => {
      const prefixCls = componentName;
      return {
        [prefixCls]: true,
        ['avatar-' + size.value]: true,
        ['avatar-' + shape.value]: true
      };
    });

    const styles = computed(() => {
      return {
        width: sizeValue.indexOf(size.value) > -1 ? '' : `${size.value}px`,
        height: sizeValue.indexOf(size.value) > -1 ? '' : `${size.value}px`,
        backgroundImage: bgImage.value ? `url(${bgImage.value})` : null,
        backgroundColor: `${bgColor.value}`
      };
    });

    const iconStyles = computed(() => {
      return !!bgIcon.value && !bgImage.value ? bgIcon.value : '';
    });

    const isShowText = computed(() => {
      return slots.default;
    });

    const activeAvatar = (e: Event) => {
      emit('active-avatar', e);
    };

    return {
      classes,
      styles,
      iconStyles,
      isShowText,
      activeAvatar
    };
  }
});
</script>
<style lang="scss">
@import 'index.scss';
</style>
