// src/packages/__VUE/toast/index.vue
<template>
  <Transition name="toast-fade" @after-leave="onAfterLeave">
    <view
      :class="toastBodyClass"
      v-show="state.mounted"
      :style="{
        bottom: center ? 'auto' : bottom + 'px',
        'background-color': coverColor
      }"
      @click="clickCover"
    >
      <view
        class="nut-toast-inner"
        :style="{
          'text-align': textAlignCenter ? 'center' : 'left',
          'background-color': bgColor
        }"
      >
        <view v-if="hasIcon" class="nut-toast-icon-wrapper">
          <nut-icon size="20" color="#ffffff" :name="icon"></nut-icon>
        </view>
        <view class="nut-toast-text" v-html="msg"></view>
      </view>
    </view>
  </Transition>
</template>
<script>
import { toRefs, toRef, reactive, computed, watch, onMounted } from 'vue';
import { createComponent } from '../../utils/create';
const { create } = createComponent('toast');
import Icon from '../icon/index.vue';
export default create({
  components: {
    [Icon.name]: Icon
  },
  props: {
    id: String,
    msg: String,
    duration: {
      type: Number,
      default: 2000
    },
    center: {
      type: Boolean,
      default: true
    },
    type: String,
    customClass: String,
    bottom: {
      type: Number,
      default: 30
    },
    size: {
      type: [String, Number],
      default: 'base'
    },
    icon: String,
    textAlignCenter: {
      type: Boolean,
      default: true
    },
    loadingRotate: {
      type: Boolean,
      default: true
    },
    bgColor: {
      type: String,
      default: 'rgba(0, 0, 0, .8)'
    },

    onClose: Function,
    unmount: Function,
    cover: {
      type: Boolean,
      default: false
    },
    coverColor: {
      type: String,
      default: 'rgba(0, 0, 0, 0)'
    },
    closeOnClickOverlay: {
      type: Boolean,
      default: false
    }
  },
  setup(props) {
    let timer;
    const state = reactive({
      mounted: false
    });
    onMounted(() => {
      state.mounted = true;
    });
    const clearTimer = () => {
      if (timer) {
        clearTimeout(timer);
        timer = null;
      }
    };
    const hide = () => {
      state.mounted = false;
    };
    const show = () => {
      clearTimer();
      if (props.duration) {
        timer = setTimeout(() => {
          hide();
        }, props.duration);
      }
    };
    const clickCover = () => {
      if (props.closeOnClickOverlay) {
        hide();
      }
    };

    if (props.duration) {
      show();
    }

    watch(
      () => props.duration,
      (val) => {
        if (val) {
          show();
        }
      }
    );

    const hasIcon = computed(() => {
      if (props.type !== 'text') {
        return true;
      } else {
        return !!props.icon;
      }
    });
    const toastBodyClass = computed(() => {
      return [
        'nut-toast',
        { 'nut-toast-center': props.center },
        { 'nut-toast-has-icon': hasIcon.value },
        { 'nut-toast-cover': props.cover },
        { 'nut-toast-loading': props.type === 'loading' },
        props.customClass,
        'nut-toast-' + props.size
      ];
    });

    const onAfterLeave = () => {
      clearTimer();
      props.unmount(props.id);
      props.onClose && props.onClose();
    };

    return {
      state,
      hide,
      clickCover,
      hasIcon,
      toastBodyClass,
      onAfterLeave
    };
  }
});
</script>
<style lang="scss">
@import 'index.scss';
</style>

// src/packages/toast/toast.tsx
import React, { FunctionComponent, useState, useLayoutEffect } from 'react'
import bem from '@/utils/bem'
import './toast.scss'
import Icon from '../icon/index'
export interface ToastProps {
  msg: string
  id?: string
  duration?: number
  center?: boolean
  type?: string
  customClass?: string
  bottom?: number
  size?: string
  icon?: string
  textAlignCenter?: boolean
  loadingRotate?: boolean
  bgColor?: string
  onClose?: (params?: string | number) => void
  unmount?: () => void
  cover?: boolean
  coverColor?: string
  closeOnClickOverlay?: boolean
  noticeKey: number | string
}
const defaultProps = {
  msg: '',
  id: '',
  duration: 2000, //显示时间(毫秒)
  center: true,
  type: 'text',
  customClass: '',
  bottom: 30,
  size: 'base',
  icon: '',
  textAlignCenter: true,
  loadingRotate: true,
  bgColor: 'rgba(0, 0, 0, .8)',
  onClose: (params?: string | number) => {},
  unmount: () => {},
  cover: false, //透明遮罩层
  coverColor: 'rgba(0, 0, 0, 0)',
  closeOnClickOverlay: false,
} as ToastProps

export const Toast: FunctionComponent<Partial<ToastProps>> = (props) => {
  const {
    msg,
    id,
    duration,
    center,
    type,
    customClass,
    bottom,
    size,
    icon,
    textAlignCenter,
    loadingRotate,
    bgColor,
    onClose,
    cover,
    coverColor,
    closeOnClickOverlay,
    noticeKey,
  } = { ...defaultProps, ...props }
  const [mounted, SetMAounted] = useState(false)
  const [isRef, SetRef] = useState(false)
  const [value, SetValue] = useState(false)
  let timer: any

  useLayoutEffect(() => {
    if (duration) {
      show()
    }
  }, [])
  const hasIcon = () => {
    if (type !== 'text') {
      return true
    } else {
      return !!icon
    }
  }
  const toastBodyClass = () => {
    return `
      nut-toast
      ${center ? 'nut-toast-center' : ''}
      ${hasIcon() ? 'nut-toast-has-icon' : ''}
      ${cover ? 'nut-toast-cover' : ''}
      ${type === 'loading' ? 'nut-toast-loading' : ''}
      ${customClass ? customClass : ''}
      ${size ? 'nut-toast-' + size : ''}
    `
  }
  const clickCover = () => {
    if (closeOnClickOverlay) {
      hide()
    }
  }
  const hide = () => {
    SetMAounted(false)
  }
  const show = () => {
    SetMAounted(true)
    clearTimer()
    if (duration) {
      timer = setTimeout(() => {
        hide()
      }, duration)
    }
  }
  const clearTimer = () => {
    if (timer) {
      clearTimeout(timer)
      timer = null
    }
  }

  const alignStyle = () => {
    return center ? 'auto' : bottom + 'px'
  }

  return mounted ? (
    <div className={toastBodyClass()} style={{ bottom: alignStyle(), backgroundColor: coverColor }}>
      <div
        className="nut-toast-inner"
        style={{
          textAlign: textAlignCenter ? 'center' : 'left',
          backgroundColor: bgColor,
        }}
      >
        {hasIcon() ? (
          <span className="nut-toast-icon-wrapper">
            <Icon name={icon} />
          </span>
        ) : null}
        <span className="nut-toast-text">{msg}</span>
      </div>
    </div>
  ) : null
}

Toast.defaultProps = defaultProps
Toast.displayName = 'NutToast'
