// src/packages/backtop/backtop.vue
<template>
  <div :class="['nut-backtop', {'show': backTop}]" :style="styles" @click.stop="click">
    <slot>
      <div class="nut-backtop-main"></div>
    </slot>
  </div>
</template>
<script>
export default {
  name: "nut-backtop",
  props: {
    distance: {
      type: Number,
      default: 200
    },
    bottom: {
      type: Number,
      default: 20
    },
    right: {
      type: Number,
      default: 10
    },
    duration: {
      type: Number,
      default: 1000
    },
    isAnimation: {
      type: Boolean,
      default: true
    },
    elId: {
      type: String,
      default: ""
    },
    zIndex: {
      type: Number,
      default: 1111
    }
  },
  data() {
    return {
      backTop: false,
      scrollEl: window
    };
  },
  mounted() {
    this.init();
  },

  activated() {
    if (this.keepAlive) {
      this.keepAlive = false;
      this.init();
    }
  },

  deactivated() {
    this.keepAlive = true;
    this.removeEventListener();
  },

  destroyed() {
    this.removeEventListener();
  },

  computed: {
    styles() {
      return {
        bottom: `${this.bottom}px`,
        right: `${this.right}px`,
        "z-index": this.zIndex
      };
    }
  },
  methods: {
    addEventListener() {
      this.scrollEl.addEventListener("scroll", this.scrollListener, false);
      this.scrollEl.addEventListener("resize", this.scrollListener, false);
    },
    removeEventListener() {
      this.scrollEl.removeEventListener("scroll", this.scrollListener, false);
      this.scrollEl.removeEventListener("resize", this.scrollListener, false);
    },
    requestAniFrame() {
      return (
        window.requestAnimationFrame ||
        window.webkitRequestAnimationFrame ||
        window.mozRequestAnimationFrame ||
        function(callback) {
          window.setTimeout(callback, 1000 / 60);
        }
      );
    },
    initCancelAniFrame() {
      let vendors = ["webkit", "moz"];
      for (
        let x = 0;
        x < vendors.length && !window.requestAnimationFrame;
        ++x
      ) {
        window.cancelAnimationFrame =
          window[vendors[x] + "CancelAnimationFrame"] ||
          window[vendors[x] + "CancelRequestAnimationFrame"];
      }
    },
    init() {
      if (this.elId && document.getElementById(this.elId)) {
        this.scrollEl = document.getElementById(this.elId);
      }
      this.addEventListener();
      this.initCancelAniFrame();
    },
    scrollListener() {
      this.scrollTop =
        this.scrollEl.pageYOffset !== undefined
          ? this.scrollEl.pageYOffset
          : this.scrollEl.scrollTop;
      this.backTop = this.scrollTop >= this.distance;
    },
    click() {
      this.startTime = +new Date();
      this.isAnimation && this.duration > 0
        ? this.scrollAnimation()
        : this.scroll();
    },
    scrollAnimation() {
      const self = this;
      var cid = self.requestAniFrame()(function fn() {
        var t =
          self.duration -
          Math.max(0, self.startTime - +new Date() + self.duration);
        var y = (t * -self.scrollTop) / self.duration + self.scrollTop;
        self.scroll(y);
        cid = self.requestAniFrame()(fn);
        if (t == self.duration) {
          window.cancelAnimationFrame(cid);
        }
      });
    },
    scroll(y = 0) {
      if (this.scrollEl === window) {
        window.scrollTo(0, y);
      } else {
        this.scrollEl.scrollTop = y;
      }
    }
  }
};
</script>

// src/packages/backtop/backtop.tsx
import React, { FunctionComponent, useLayoutEffect, useEffect, useState, useRef } from 'react'
import './backtop.scss'
import Icon from '../icon'
declare const window: any
export interface BackTopProps {
  bottom: number
  right: number
  elId: string
  distance: number
  zIndex: number
  isAnimation: boolean
  duration: number
  children?: HTMLElement | any
  backTopClick: (event: MouseEvent) => void
}
const defaultProps = {
  bottom: 20,
  right: 10,
  elId: '',
  distance: 200,
  zIndex: 10,
  isAnimation: true,
  duration: 1000,
} as BackTopProps

export const BackTop: FunctionComponent<Partial<BackTopProps>> = (props) => {
  const { children, bottom, right, elId, distance, zIndex, isAnimation, duration, backTopClick } = {
    ...defaultProps,
    ...props,
  }
  const [backTop, SetBackTop] = useState(false)
  const [scrollTop, SetScrollTop] = useState(0)
  const [startTime, SetStartTime] = useState(0)
  let scrollEl: any = elId ? useRef<HTMLElement>(document.getElementById(elId)) : (window as Window)
  //初始化
  useEffect(() => {
    init()
    return () => removeEventListener()
  }, [])

  const init = () => {
    if (elId && document.getElementById(elId)) {
      scrollEl = document.getElementById(elId) as HTMLElement | Window
    }
    addEventListener()
    initCancelAniFrame()
  }
  const scrollListener = () => {
    let top: any = null
    if (scrollEl instanceof Window) {
      top = scrollEl.pageYOffset
      SetScrollTop(top)
    } else {
      top = scrollEl.scrollTop
      SetScrollTop(top)
    }
    let showBtn = top >= distance

    SetBackTop(showBtn)
  }

  const scroll = (y = 0) => {
    if (scrollEl instanceof Window) {
      window.scrollTo(0, y)
    } else {
      let dom = document.getElementById(elId)
      dom?.scrollTo(0, y)
      //   scrollEl.scrollTop = y
    }
  }

  const scrollAnimation = () => {
    let cid = requestAniFrame()(function fn() {
      var t = duration - Math.max(0, startTime - +new Date() + duration)
      var y = (t * -scrollTop) / duration + scrollTop
      scroll(y)
      cid = requestAniFrame()(fn)
      if (t == duration || y == 0) {
        window.cancelAnimationFrame(cid)
      }
    })
  }

  const initCancelAniFrame = () => {
    window.cancelAnimationFrame = window.webkitCancelAnimationFrame
  }
  //防频
  const requestAniFrame = () => {
    return (
      window.requestAnimationFrame ||
      window.webkitRequestAnimationFrame ||
      window.mozRequestAnimationFrame ||
      function (callback: any) {
        window.setTimeout(callback, 1000 / 60)
      }
    )
  }
  //监听事件
  function addEventListener() {
    scrollEl.addEventListener('scroll', scrollListener, false)
    scrollEl.addEventListener('resize', scrollListener, false)
  }
  //移除监听事件
  function removeEventListener() {
    scrollEl.removeEventListener('scroll', scrollListener, false)
    scrollEl.removeEventListener('resize', scrollListener, false)
  }
  //返回顶部点击事件
  const goTop = (e: any) => {
    backTopClick(e)
    let otime = +new Date()
    SetStartTime(otime)
    isAnimation && duration > 0 ? scrollAnimation() : scroll()
  }

  const backTopClass = {
    right: `${right}px`,
    bottom: `${bottom}px`,
    zIndex: zIndex,
  }

  return (
    <div className={`nut-backtop ${backTop ? 'show' : ''}`} style={backTopClass} onClick={goTop}>
      {children ? children : <Icon size="19px" className="nut-backtop-main" name="top"></Icon>}
    </div>
  )
}

BackTop.defaultProps = defaultProps
BackTop.displayName = 'NutBackTop'
