// src/packages/backtop/index.vue
<template>
  <div :class="classes" :style="style" @click.stop="click">
    <slot>
      <nut-icon size="19px" class="nut-backtop-main" name="top"></nut-icon>
    </slot>
  </div>
</template>

<script lang="ts">
import {
  computed,
  onMounted,
  onUnmounted,
  onActivated,
  onDeactivated,
  reactive
} from 'vue';
import { createComponent } from '@/utils/create';
const { componentName, create } = createComponent('backtop');
export default create({
  props: {
    bottom: {
      type: Number,
      default: 20
    },
    right: {
      type: Number,
      default: 10
    },
    elId: {
      type: String,
      default: ''
    },
    distance: {
      type: Number,
      default: 200
    },
    zIndex: {
      type: Number,
      default: 10
    },
    isAnimation: {
      type: Boolean,
      default: true
    },
    duration: {
      type: Number,
      default: 1000
    }
  },
  emits: ['click'],
  setup(props, { emit }) {
    const state = reactive({
      backTop: false,
      scrollTop: 0,
      scrollEl: window as HTMLElement | Window,
      startTime: 0,
      keepAlive: false
    });
    let scrollEl: Window | HTMLElement = window;
    const classes = computed(() => {
      const prefixCls = componentName;
      return {
        [prefixCls]: true,
        show: state.backTop
      };
    });
    const style = computed(() => {
      return {
        right: `${props.bottom}px`,
        bottom: `${props.right}px`,
        zIndex: props.zIndex
      };
    });

    function scrollListener() {
      if (state.scrollEl instanceof Window) {
        state.scrollTop = state.scrollEl.pageYOffset;
      } else {
        state.scrollTop = state.scrollEl.scrollTop;
      }
      state.backTop = state.scrollTop >= props.distance;
    }

    function scroll(y = 0) {
      if (state.scrollEl instanceof Window) {
        window.scrollTo(0, y);
      } else {
        state.scrollEl.scrollTop = y;
      }
    }

    function scrollAnimation() {
      let cid = requestAniFrame()(function fn() {
        var t =
          props.duration -
          Math.max(0, state.startTime - +new Date() + props.duration);
        var y = (t * -state.scrollTop) / props.duration + state.scrollTop;
        scroll(y);
        cid = requestAniFrame()(fn);
        if (t == props.duration || y == 0) {
          window.cancelAnimationFrame(cid);
        }
      });
    }

    function addEventListener() {
      state.scrollEl.addEventListener('scroll', scrollListener, false);
      state.scrollEl.addEventListener('resize', scrollListener, false);
    }

    function removeEventListener() {
      state.scrollEl.removeEventListener('scroll', scrollListener, false);
      state.scrollEl.removeEventListener('resize', scrollListener, false);
    }

    function initCancelAniFrame() {
      window.cancelAnimationFrame = window.webkitCancelAnimationFrame;
    }

    function requestAniFrame() {
      return (
        window.requestAnimationFrame ||
        window.webkitRequestAnimationFrame ||
        function(callback) {
          window.setTimeout(callback, 1000 / 60);
        }
      );
    }

    function click(e: MouseEvent) {
      state.startTime = +new Date();
      props.isAnimation && props.duration > 0 ? scrollAnimation() : scroll();
      emit('click', e);
    }

    function init() {
      if (props.elId && document.getElementById(props.elId)) {
        state.scrollEl = document.getElementById(props.elId) as
          | HTMLElement
          | Window;
      }
      addEventListener();
      initCancelAniFrame();
    }

    onMounted(() => {
      init();
    });

    onUnmounted(() => {
      removeEventListener();
    });

    onActivated(() => {
      if (state.keepAlive) {
        state.keepAlive = false;
        init();
      }
    });

    onDeactivated(() => {
      state.keepAlive = true;
      removeEventListener();
    });

    return {
      state,
      classes,
      style,
      click
    };
  }
});
</script>

<style lang="scss">
@import 'index.scss';
</style>

// src/packages/backtop/backtop.tsx
import React, { FunctionComponent, useLayoutEffect, useEffect, useState, useRef } from 'react'
import './backtop.scss'
import Icon from '../icon'
declare const window: any
export interface BackTopProps {
  bottom: number
  right: number
  elId: string
  distance: number
  zIndex: number
  isAnimation: boolean
  duration: number
  children?: HTMLElement | any
  backTopClick: (event: MouseEvent) => void
}
const defaultProps = {
  bottom: 20,
  right: 10,
  elId: '',
  distance: 200,
  zIndex: 10,
  isAnimation: true,
  duration: 1000,
} as BackTopProps

export const BackTop: FunctionComponent<Partial<BackTopProps>> = (props) => {
  const { children, bottom, right, elId, distance, zIndex, isAnimation, duration, backTopClick } = {
    ...defaultProps,
    ...props,
  }
  const [backTop, SetBackTop] = useState(false)
  const [scrollTop, SetScrollTop] = useState(0)
  const [startTime, SetStartTime] = useState(0)
  let scrollEl: any = elId ? useRef<HTMLElement>(document.getElementById(elId)) : (window as Window)
  //初始化
  useEffect(() => {
    init()
    return () => removeEventListener()
  }, [])

  const init = () => {
    if (elId && document.getElementById(elId)) {
      scrollEl = document.getElementById(elId) as HTMLElement | Window
    }
    addEventListener()
    initCancelAniFrame()
  }
  const scrollListener = () => {
    let top: any = null
    if (scrollEl instanceof Window) {
      top = scrollEl.pageYOffset
      SetScrollTop(top)
    } else {
      top = scrollEl.scrollTop
      SetScrollTop(top)
    }
    let showBtn = top >= distance

    SetBackTop(showBtn)
  }

  const scroll = (y = 0) => {
    if (scrollEl instanceof Window) {
      window.scrollTo(0, y)
    } else {
      let dom = document.getElementById(elId)
      dom?.scrollTo(0, y)
      //   scrollEl.scrollTop = y
    }
  }

  const scrollAnimation = () => {
    let cid = requestAniFrame()(function fn() {
      var t = duration - Math.max(0, startTime - +new Date() + duration)
      var y = (t * -scrollTop) / duration + scrollTop
      scroll(y)
      cid = requestAniFrame()(fn)
      if (t == duration || y == 0) {
        window.cancelAnimationFrame(cid)
      }
    })
  }

  const initCancelAniFrame = () => {
    window.cancelAnimationFrame = window.webkitCancelAnimationFrame
  }
  //防频
  const requestAniFrame = () => {
    return (
      window.requestAnimationFrame ||
      window.webkitRequestAnimationFrame ||
      window.mozRequestAnimationFrame ||
      function (callback: any) {
        window.setTimeout(callback, 1000 / 60)
      }
    )
  }
  //监听事件
  function addEventListener() {
    scrollEl.addEventListener('scroll', scrollListener, false)
    scrollEl.addEventListener('resize', scrollListener, false)
  }
  //移除监听事件
  function removeEventListener() {
    scrollEl.removeEventListener('scroll', scrollListener, false)
    scrollEl.removeEventListener('resize', scrollListener, false)
  }
  //返回顶部点击事件
  const goTop = (e: any) => {
    backTopClick(e)
    let otime = +new Date()
    SetStartTime(otime)
    isAnimation && duration > 0 ? scrollAnimation() : scroll()
  }

  const backTopClass = {
    right: `${right}px`,
    bottom: `${bottom}px`,
    zIndex: zIndex,
  }

  return (
    <div className={`nut-backtop ${backTop ? 'show' : ''}`} style={backTopClass} onClick={goTop}>
      {children ? children : <Icon size="19px" className="nut-backtop-main" name="top"></Icon>}
    </div>
  )
}

BackTop.defaultProps = defaultProps
BackTop.displayName = 'NutBackTop'
