// src/packages/step/step.tsx
import React, { FunctionComponent, useContext } from 'react'
import { DataContext } from '@/packages/steps/UserContext'
import bem from '@/utils/bem'
import classNames from 'classnames'
import Icon from '@/packages/icon'
import './step.scss'

export interface StepProps {
  title: string
  content: string
  activeIndex: number
  icon: string
  size: string
  renderContent: () => React.ReactNode
}
const defaultProps = {
  title: '',
  content: '',
  activeIndex: 0,
  icon: '',
  size: '12px',
} as StepProps
export const Step: FunctionComponent<Partial<StepProps> & React.HTMLAttributes<HTMLDivElement>> = (
  props
) => {
  const { children, title, content, activeIndex, icon, size, renderContent } = {
    ...defaultProps,
    ...props,
  }
  const parent: any = useContext(DataContext)

  const dot = parent.propSteps.progressDot
  const getCurrentStatus = () => {
    const index = activeIndex
    if (index < +parent.propSteps.current) return 'finish'
    return index === +parent.propSteps.current ? 'process' : 'wait'
  }

  const b = bem('step')
  const classes = classNames(
    {
      [`${b('')}-${getCurrentStatus()}`]: true,
    },
    b('')
  )
  return (
    <div className={classes}>
      <div className="nut-step-head">
        <div className="nut-step-line"></div>
        <div className={`nut-step-icon ${!dot ? (icon ? 'is-icon' : 'is-text') : ''}`}>
          {icon ? (
            <Icon className="nut-step-icon-inner" name={icon} size={size} />
          ) : dot ? (
            <span></span>
          ) : (
            <span className="nut-step-inner">{activeIndex}</span>
          )}
        </div>
      </div>
      <div className="nut-step-main">
        <span className="nut-step-title">{title}</span>
        {content && <span className="nut-step-content">{content}</span>}
        {renderContent && <span className="nut-step-content">{renderContent()}</span>}
      </div>
    </div>
  )
}

Step.defaultProps = defaultProps
Step.displayName = 'NutStep'

// src/packages/__VUE/step/step.vue
<template>
  <view :class="classes" @click="handleClickStep">
    <view class="nut-step-head">
      <view class="nut-step-line"></view>
      <view class="nut-step-icon" :class="[!dot ? 'is-icon' : '']">
        <view class="nut-step-icon-inner">
          <slot name="icon">
            <template v-if="!dot">
              <view class="nut-step-inner">{{ index + 1 }}</view>
            </template>
          </slot>
        </view>
      </view>
    </view>
    <view class="nut-step-main">
      <view class="nut-step-title">
        <span v-if="!$slots.title">{{ title }}</span>
        <slot name="title"></slot>
      </view>
      <view v-if="content || $slots.content" class="nut-step-content">
        <span v-if="!$slots.content" v-html="content"></span>
        <slot name="content"></slot>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useParent } from '@/packages/utils'
import { STEPS_KEY } from '../steps/types'

defineOptions({
  name: 'NutStep'
})

export type StepProps = Partial<{
  title: string
  content: string
}>

withDefaults(defineProps<StepProps>(), {
  title: '',
  content: ''
})

const { index, parent } = useParent(STEPS_KEY)

const getCurrentStatus = () => {
  const activeIndex = index.value + 1
  console.log(activeIndex, +parent.props.current)
  if (activeIndex < +parent.props.current) return 'finish'
  return activeIndex === +parent.props.current ? 'process' : 'wait'
}

const status = computed(() => getCurrentStatus())

const dot = computed(() => parent.props.progressDot)

const classes = computed(() => {
  const prefixCls = 'nut-step'
  return {
    [prefixCls]: true,
    [`${prefixCls}-${status.value}`]: true
  }
})

const handleClickStep = () => {
  parent.onEmit(index.value + 1)
}
</script>
