// src/packages/__VUE/switch/switch.vue
<template>
  <view :class="classes" :style="style" @click="onClick">
    <view class="nut-switch-button">
      <slot v-if="loading" name="icon">
        <Loading1 name="loading" :color="activeColor" />
      </slot>
      <template v-if="activeText">
        <view v-show="isActive" class="nut-switch-label open">{{ activeText }}</view>
        <view v-show="!isActive" class="nut-switch-label close">{{ inactiveText }}</view>
      </template>
    </view>
  </view>
</template>

<script setup lang="ts">
import { computed, watch } from 'vue';
import { Loading1 } from '@nutui/icons-vue';
import { useFormDisabled } from '../form/common';

defineOptions({
  name: 'NutSwitch'
});

export type SwitchProps = Partial<{
  modelValue: string | number | boolean;
  disabled: boolean;
  activeColor: string;
  inactiveColor: string;
  activeText: string;
  inactiveText: string;
  activeValue: string | number | boolean;
  inactiveValue: string | number | boolean;
  loading: boolean;
  /**
   * @deprecated Please use `disabled` prop instead.
   */
  disable: boolean;
}>;

const props = withDefaults(defineProps<SwitchProps>(), {
  modelValue: false,
  disabled: false,
  activeColor: '',
  inactiveColor: '',
  activeText: '',
  inactiveText: '',
  activeValue: true,
  inactiveValue: false,
  loading: false,
  disable: false
});

const emit = defineEmits(['change', 'update:modelValue', 'update:loading']);

const legacyDisabled = computed(() => props.disabled || props.disable);
const disabled = useFormDisabled(legacyDisabled);
const isActive = computed(() => props.modelValue === props.activeValue);
const classes = computed(() => {
  const prefixCls = 'nut-switch';
  return {
    [prefixCls]: true,
    [isActive.value ? 'nut-switch-open' : 'nut-switch-close']: true,
    [`${prefixCls}-disabled`]: disabled.value,
    [`${prefixCls}-base`]: true
  };
});

const style = computed(() => {
  return {
    backgroundColor: isActive.value ? props.activeColor : props.inactiveColor
  };
});

let updateType = '';

const onClick = (event: Event) => {
  if (props.loading || disabled.value) return;
  const value = isActive.value ? props.inactiveValue : props.activeValue;
  updateType = 'click';
  emit('update:modelValue', value);
  emit('change', value, event);
};

watch(
  () => props.modelValue,
  (v) => {
    if (updateType == 'click') {
      updateType = '';
    } else {
      emit('change', v);
    }
  }
);
</script>

// src/packages/switch/switch.tsx
import React, { FunctionComponent, useState, useEffect } from 'react'
import './switch.scss'
import bem from '@/utils/bem'

export interface SwitchProps {
  isAsync: boolean
  checked: boolean
  disable: boolean
  activeColor: string
  inactiveColor: string
  activeText: string
  inactiveText: string
  change: (val: boolean, event: React.MouseEvent) => void
}
const defaultProps = {
  isAsync: false,
  checked: false,
  disable: false,
  activeColor: '',
  inactiveColor: '',
  activeText: '',
  inactiveText: '',
} as SwitchProps
export const Switch: FunctionComponent<Partial<SwitchProps>> = (props) => {
  const {
    isAsync,
    checked,
    disable,
    activeColor,
    inactiveColor,
    activeText,
    inactiveText,
    change,
  } = {
    ...defaultProps,
    ...props,
  }

  const [value, setValue] = useState(false)
  const b = bem('switch')

  useEffect(() => {
    setValue(checked)
  }, [checked])

  const classes = () => {
    return `${b()} ${value ? 'switch-open' : 'switch-close'} ${
      disable ? `${b()}-disable` : ''
    } ${`${b()}-base`}`
  }

  const style = () => {
    return {
      backgroundColor: value ? activeColor : inactiveColor,
    }
  }

  const onClick = (event: React.MouseEvent) => {
    if (disable) return
    if (!isAsync) {
      setValue(!value)
    }
    change && change(!value, event)
  }
  return (
    <div className={classes()} onClick={(e) => onClick(e)} style={style()}>
      <div className="switch-button">
        {!value && <div className="close-line"></div>}
        {activeText && (
          <>
            {value ? (
              <div className={`${b('label')} open`}>{activeText}</div>
            ) : (
              <div className={`${b('label')} close`}>{inactiveText}</div>
            )}
          </>
        )}
      </div>
    </div>
  )
}

Switch.defaultProps = defaultProps
Switch.displayName = 'NutSwitch'
