// src/packages/fixednav/fixednav.tsx
import React, { FunctionComponent, useState, useEffect, MouseEvent, HTMLProps } from 'react'
import { Icon } from '../icon/icon'
import { Overlay } from '../overlay/overlay'
import classNames from 'classnames'

import './fixednav.scss'

export interface FixedNavProps {
  prefixCls: string
  visible: boolean
  overlay: boolean
  navList: Array<object>
  activeText: string
  unActiveText: string
  position: object
  type: string
  change: Function
  selected: Function
  slotList: HTMLProps<HTMLElement>
  slotBtn: HTMLProps<HTMLElement>
}

const defaultProps = {
  prefixCls: 'nut-fixednav',
  activeText: '收起导航',
  unActiveText: '快速导航',
  position: {
    top: 'auto',
    bottom: 'auto',
  },
  type: 'right',
} as FixedNavProps

export const FixedNav: FunctionComponent<
  Partial<FixedNavProps> & React.HTMLAttributes<HTMLDivElement>
> = (props) => {
  const {
    prefixCls,
    children,
    overlay,
    visible,
    navList,
    activeText,
    unActiveText,
    position,
    change,
    selected,
    type,
    slotList,
    slotBtn,
  } = { ...defaultProps, ...props }

  const selectCb = (event: MouseEvent, item: any) => {
    selected(item, event)
  }

  const updateValue = (value: boolean = !visible) => {
    change(value)
  }

  const [classNames, setClassNames] = useState('')

  const classes = () => {
    return `${prefixCls} ${type} ${visible ? 'active' : ''}`
  }

  useEffect(() => {
    setClassNames(classes())
  }, [visible])

  return (
    <div className={`${classNames}`} style={position}>
      {overlay && (
        <Overlay visible={visible} zIndex={200} onClick={() => updateValue(false)}></Overlay>
      )}
      <div className="list">
        {slotList ? (
          slotList
        ) : (
          <div className="nut-fixednav__list">
            {navList.map((item: any, index) => {
              return (
                <div
                  className="nut-fixednav__list-item"
                  onClick={(event) => selectCb(event, item)}
                  key={item.id || index}
                >
                  <img src={item.icon} />
                  <div className="span">{item.text}</div>
                  {item.num && <div className="b">{item.num}</div>}
                </div>
              )
            })}
          </div>
        )}
      </div>

      <div className="nut-fixednav__btn" onClick={() => updateValue()}>
        {slotBtn ? (
          slotBtn
        ) : (
          <>
            <Icon name="left" color="#fff" />
            <div className="text">{visible ? activeText : unActiveText}</div>
          </>
        )}
      </div>
    </div>
  )
}

FixedNav.defaultProps = defaultProps
FixedNav.displayName = 'NutFixedNav'

// src/packages/fixednav/fixednav.vue
<template>
  <div class="nut-fixednav" :class="styled">
    <div style="position:relative;z-index:1">
      <nut-popup v-model="defaultActive"></nut-popup>
    </div>
    <slot name="list">
      <ul class="fixed-list">
        <li v-for="(item,index) in navList" @click="selected(item,$event)" :key="item.id||index">
          <img :src="item.icon" />
          <span>{{item.text}}</span>
          <b v-if="item.num">{{item.num}}</b>
        </li>
      </ul>
    </slot>

    <div class="fixed-btn" @click="defaultActive=!defaultActive">
      <slot name="btn">
        <img
          src="https://img14.360buyimg.com/imagetools/jfs/t1/149975/30/1615/368/5ef86176Eb75bae46/5f70ae80a2d567b4.png" />
        <span>{{defaultActive?activeText:unActiveText}}</span>
      </slot>
    </div>
  </div>
</template>
<script>
export default {
  name: 'nut-fixednav',
  props: {
    active: {
      type: Boolean,
      default: false
    },
    navList: {
      default: () => [],
      type: Array
    },
    activeText: {
      default: '收起导航',
      type: String
    },
    unActiveText: {
      default: '快速导航',
      type: String
    },
    type: {
      default: 'right',
      type: String
    }
  },
  computed: {
    styled() {
      return {
        active: this.defaultActive,
        [this.defaultType]: true
      };
    }
  },
  watch: {
    defaultActive(newV, oldV) {
      this.$emit('update:active', newV);
    }
  },
  data() {
    return {
      defaultActive: false,
      defaultType: ''
    };
  },
  mounted() {
    this.defaultActive = this.active;
    this.defaultType = this.type;
  },
  methods: {
    selected(item, $event) {
      this.$emit('selected', { item, $event });
    }
  }
};
</script>
