// src/packages/__VUE/tag/tag.vue
<template>
  <view :class="classes" :style="style" @click="onClick">
    <slot></slot>
    <Close v-if="closeable" class="nut-tag--close" width="12px" height="12px" @click.stop="onClose"></Close>
  </view>
</template>

<script setup lang="ts">
import { CSSProperties, computed } from 'vue';
import { Close } from '@nutui/icons-vue';
import { TagType } from './types';

defineOptions({
  name: 'NutTag'
});

export type TagProps = Partial<{
  color: string;
  textColor: string;
  type: TagType;
  plain: boolean;
  round: boolean;
  mark: boolean;
  closeable: boolean;
}>;

const props = withDefaults(defineProps<TagProps>(), {
  color: '',
  textColor: '',
  type: 'default',
  plain: false,
  round: false,
  mark: false,
  closeable: false
});

const emits = defineEmits(['close', 'click']);

const classes = computed(() => {
  const prefixCls = 'nut-tag';
  return {
    [prefixCls]: true,
    [`${prefixCls}--${props.type}`]: props.type,
    [`${prefixCls}--plain`]: props.plain,
    [`${prefixCls}--round`]: props.round,
    [`${prefixCls}--mark`]: props.mark
  };
});

const style = computed<CSSProperties>(() => {
  const style: CSSProperties = {};
  if (props.textColor) {
    style.color = props.textColor;
  } else if (props.color && props.plain) {
    style.color = props.color;
  }
  if (props.plain) {
    style.background = '#fff';
    style.borderColor = props.color;
  } else if (props.color) {
    style.background = props.color;
  }
  return style;
});

const onClose = (event: Event) => {
  emits('close', event);
};

const onClick = (event: Event) => {
  emits('click', event);
};
</script>

// src/packages/tag/tag.tsx
import React, {
  CSSProperties,
  FunctionComponent,
  MouseEventHandler,
  useEffect,
  useState,
} from 'react'
import './tag.scss'
import classNames from 'classnames'
import Icon from '@/packages/icon'
export interface TagProps {
  type: TagType
  color: string
  textColor: string
  plain: boolean
  round: boolean
  mark: boolean
  closeable: boolean
  isShow: boolean
  prefixCls: string
  onClick: (e: MouseEvent) => void
}

export type TagType = 'default' | 'primary' | 'success' | 'warning' | 'danger'
const defaultProps = {
  type: 'default',
  color: '',
  textColor: '',
  plain: false,
  round: false,
  mark: false,
  closeable: false,
  isShow: true,
  prefixCls: 'nut-tag',
  onClick: (e: MouseEvent) => {},
} as TagProps
export const Tag: FunctionComponent<Partial<TagProps>> = (props) => {
  const {
    color,
    plain,
    type,
    round,
    prefixCls,
    children,
    mark,
    closeable,
    textColor,
    isShow,
    onClick,
  } = {
    ...defaultProps,
    ...props,
  }
  const [btnName, setBtnName] = useState('')
  useEffect(() => {
    setBtnName(classes())
  }, [type, color, textColor, plain, round, mark, closeable, prefixCls, isShow, onClick])
  const classes = () => {
    const prefixCls = 'nut-tag'
    return `${prefixCls}
    ${type ? `${prefixCls}--${type}` : ''}
    ${plain ? `${prefixCls}--plain` : ''}
    ${round ? `${prefixCls}--round` : ''}
    ${mark ? `${prefixCls}--mark` : ''}
    ${closeable ? `${prefixCls}--close` : ''}`
  }
  const handleClick = (e: any) => {
    if (props.onClick) {
      props.onClick(e)
    }
  }
  const getStyle = () => {
    const style: CSSProperties = {}
    if (textColor) {
      style.color = textColor
      if (plain) {
        style.background = '#fff'
      } else {
        if (color) {
          style.background = color
        }
      }
    } else {
      if (color) {
        style.color = '#fff'
        style.background = color
      }
    }
    return style
  }
  return (
    <div>
      {closeable ? (
        isShow ? (
          <div className={`${btnName}`} style={getStyle()} onClick={(e) => handleClick(e)}>
            {children && <span className="text">{children}</span>}
            {closeable && (
              <Icon className="_icon" name="close" size="12" onClick={(e) => handleClick(e)}></Icon>
            )}
          </div>
        ) : (
          ''
        )
      ) : (
        <div className={`${btnName}`} style={getStyle()} onClick={(e) => handleClick(e)}>
          {children && <span className="text">{children}</span>}
        </div>
      )}
    </div>
  )
}

Tag.defaultProps = defaultProps
Tag.displayName = 'NutTag'
