// src/packages/__VUE/barrage/index.vue
<template>
  <view ref="dmBody" :class="classes">
    <view ref="dmContainer" class="dmContainer"></view>
    <!-- <view v-for="(item, index) of danmuList" :key="'danmu'+index" class="dmitem">
      {{item}}
    </view> -->
  </view>
</template>
<script lang="ts">
import {
  computed,
  onMounted,
  ref,
  reactive,
  toRefs,
  watch,
  nextTick
} from 'vue';
import { createComponent } from '../../utils/create';
const { componentName, create } = createComponent('barrage');

export default create({
  props: {
    danmu: {
      type: Array,
      default: () => []
    },
    frequency: {
      type: Number,
      default: 200
    },
    speeds: {
      type: Number,
      default: 2000
    },
    rows: {
      type: Number,
      default: 3
    },
    top: {
      type: Number,
      default: 10
    },
    loop: {
      type: Boolean,
      default: true
    }
  },
  emits: ['click'],

  setup(props, { emit }) {
    const classes = computed(() => {
      const prefixCls = componentName;
      return {
        [prefixCls]: true
      };
    });

    let dmBody = ref<HTMLDivElement>(document.createElement('div'));
    let dmContainer = ref<HTMLDivElement>(document.createElement('div'));

    let timer: number = 0;
    const danmuList = ref<any[]>(props.danmu);
    const rows = ref<number>(props.rows);
    const top = ref<number>(props.top);
    const index = ref<number>(0);
    const speeds = props.speeds;
    const danmuCWidth = ref(0);

    onMounted(() => {
      danmuCWidth.value = dmBody.value.offsetWidth;
      run();
    });

    watch(
      () => props.danmu,
      (newValue, oldVlaue) => {
        danmuList.value = [...newValue];
      }
    );

    const add = (word: string) => {
      const _index = index.value % danmuList.value.length;
      danmuList.value.splice(_index, 0, word);
    };

    const run = () => {
      clearInterval(timer);
      timer = 0;
      timer = setInterval(() => {
        play();
        run();
      }, props.frequency);
    };

    const play = () => {
      const _index = props.loop
        ? index.value % danmuList.value.length
        : index.value;
      let el = document.createElement(`view`);
      el.innerHTML = danmuList.value[_index] as string;
      el.classList.add('dmitem');
      dmContainer.value.appendChild(el);

      nextTick(() => {
        const width = el.offsetWidth;
        const height = el.offsetHeight;
        el.classList.add('move');
        el.style.animationDuration = `${speeds}ms`;
        el.style.top = (_index % rows.value) * (height + top.value) + 'px';
        el.style.width = width + 20 + 'px';
        // el.style.left = "-"+(_index % rows.value) + 'px';
        el.style.setProperty('--move-distance', `-${danmuCWidth.value}px`);
        el.dataset.index = `${_index}`;
        el.addEventListener('animationend', () => {
          dmContainer.value.removeChild(el);
        });
        index.value++;
      });
    };
    return { classes, danmuList, dmBody, dmContainer, add };
  }
});
</script>

<style lang="scss">
@import 'index.scss';
</style>

// src/packages/barrage/barrage.tsx
import React, { ForwardRefRenderFunction, useEffect, useRef, useImperativeHandle } from 'react'
import classNames from 'classnames'
import bem from '@/utils/bem'
import './barrage.scss'

export interface BarrageProps {
  className: string
  style: React.CSSProperties
  danmu: Array<string>
  frequency: number
  loop: boolean
  speeds: number
  rows: number
  top: number
}
const defaultProps = {
  danmu: [''],
  frequency: 500,
  loop: true,
  speeds: 2000,
  rows: 3,
  top: 10,
}
const InternalBarrage: ForwardRefRenderFunction<unknown, Partial<BarrageProps>> = (props, ref) => {
  const { className, frequency, loop, danmu, speeds, rows, top, ...restProps } = {
    ...defaultProps,
    ...props,
  }
  const dmBody = useRef<HTMLDivElement>(null)
  const dmContainer = useRef<HTMLDivElement>(null)
  const danmuCWidth = useRef(0)
  const timer = useRef(0)
  const index = useRef(0)

  const b = bem('barrage')
  const classes = classNames(className, b(''))

  useImperativeHandle(ref, () => ({
    add: (word: string) => {
      const _index = index.current % danmu.length
      danmu.splice(_index, 0, word)
    },
  }))

  useEffect(() => {
    if (dmBody.current) {
      danmuCWidth.current = dmBody.current.offsetWidth
      run()
    }
    return () => {
      clearInterval(timer.current)
    }
  }, [])

  const run = () => {
    clearInterval(timer.current)
    timer.current = setInterval(() => {
      play()
      run()
    }, frequency)
  }

  const play = () => {
    const _index = loop ? index.current % danmu.length : index.current
    let el = document.createElement(`div`)
    el.innerHTML = danmu[_index] as string
    el.classList.add('dmitem')
    ;(dmContainer.current as HTMLDivElement).appendChild(el)

    const width = el.offsetWidth
    const height = el.offsetHeight
    el.classList.add('move')
    el.style.animationDuration = `${speeds}ms`
    el.style.top = (_index % rows) * (height + top) + 20 + 'px'
    el.style.width = width + 20 + 'px'
    el.style.setProperty('--move-distance', `-${danmuCWidth.current}px`)
    el.dataset.index = `${_index}`
    el.addEventListener('animationend', () => {
      ;(dmContainer.current as HTMLDivElement).removeChild(el)
    })
    index.current++
  }

  return (
    <div className={classes} ref={dmBody} {...restProps}>
      <div ref={dmContainer} className="dmContainer"></div>
    </div>
  )
}

export const Barrage = React.forwardRef<unknown, Partial<BarrageProps>>(InternalBarrage)

Barrage.defaultProps = defaultProps
Barrage.displayName = 'NutBarrage'
