// src/packages/price/price.tsx
import React, { FunctionComponent } from 'react'
import './price.scss'
import bem from '@/utils/bem'

export interface PriceProps {
  price: number | string
  needSymbol: boolean
  symbol: string
  decimalDigits: number
  thousands: boolean
}
const defaultProps = {
  price: 0,
  needSymbol: true,
  symbol: '&yen;',
  decimalDigits: 2,
  thousands: false,
} as PriceProps
export const Price: FunctionComponent<Partial<PriceProps>> = (props) => {
  const { price, needSymbol, symbol, decimalDigits, thousands } = { ...defaultProps, ...props }
  const b = bem('price')
  const showSymbol = () => {
    return { __html: (props.needSymbol ? props.symbol : '') || '' }
  }
  const checkPoint = (price: string | number) => {
    return String(price).indexOf('.') > 0
  }
  const formatThousands = (num: any) => {
    if (Number(num) == 0) {
      num = 0
    }
    if (checkPoint(num)) {
      num = Number(num).toFixed(decimalDigits)
      num = typeof num.split('.') === 'string' ? num.split('.') : num.split('.')[0]
    } else {
      num = num.toString()
    }
    if (props.thousands) {
      return (num || 0).toString().replace(/(\d)(?=(?:\d{3})+$)/g, '$1,')
    } else {
      return num
    }
  }
  const formatDecimal = (decimalNum: any) => {
    if (Number(decimalNum) == 0) {
      decimalNum = 0
    }
    if (checkPoint(decimalNum)) {
      decimalNum = Number(decimalNum).toFixed(decimalDigits)
      decimalNum = typeof decimalNum.split('.') === 'string' ? 0 : decimalNum.split('.')[1]
    } else {
      decimalNum = decimalNum.toString()
    }
    const result = '0.' + decimalNum
    const resultFixed = Number(result).toFixed(decimalDigits)
    return String(resultFixed).substring(2, resultFixed.length)
  }
  return (
    <div className="nut-price">
      {needSymbol ? (
        <div className={`${b('symbol')}`} dangerouslySetInnerHTML={showSymbol()}></div>
      ) : null}
      <div className={`${b('big')}`}>{formatThousands(price)}</div>
      <div className={`${b('point')}`}>.</div>
      <div className={`${b('small')}`}>{formatDecimal(price)}</div>
    </div>
  )
}

Price.defaultProps = defaultProps
Price.displayName = 'NutPrice'

// src/packages/price/index.vue
<template>
  <view :class="classes" v-html="priceShow"> </view>
</template>

<script lang="ts">
import { computed } from 'vue';
import { createComponent } from '@/utils/create';
const { componentName, create } = createComponent('price');

export default create({
  props: {
    price: {
      type: [Number, String],
      default: 0
    },
    needSymbol: {
      type: Boolean,
      default: true
    },
    symbol: {
      type: String,
      default: '&yen;'
    },
    decimalDigits: {
      type: Number,
      default: 2
    },
    thousands: {
      type: Boolean,
      default: false
    }
  },

  setup(props) {
    const priceShow = computed(() => {
      const symbol = props.needSymbol
        ? `<view class="${componentName}--symbol">${props.symbol}</view>`
        : '';
      return symbol + formatToHump(props.price);
    });
    const classes = computed(() => {
      return {
        [componentName]: true
      };
    });

    const checkPoint = (price: string | number) => {
      return String(price).indexOf('.') > 0;
    };
    const formatThousands = (num: string | number) => {
      if (props.thousands) {
        return (num || 0).toString().replace(/(\d)(?=(?:\d{3})+$)/g, '$1,');
      } else {
        return num;
      }
    };
    const formatDecimal = (decimalNum: string | number) => {
      const result = '0.' + decimalNum;
      const resultFixed = Number(result).toFixed(props.decimalDigits);
      return String(resultFixed).substring(2, resultFixed.length);
    };

    const renderPrice = (price: string[] | string) => {
      return `<view class="${componentName}--big">${formatThousands(
        typeof price === 'string' ? price : price[0]
      )}</view><view class="${componentName}--point">.</view><view class="${componentName}--small">${formatDecimal(
        typeof price === 'string' ? 0 : price[1]
      )}</view>`;
    };

    const formatToHump = (price: string | number) => {
      if (Number(price) == 0) {
        return 0;
      }
      if (checkPoint(price)) {
        price = Number(price);
        return renderPrice((price + '').split('.'));
      } else {
        return renderPrice(price.toString());
      }
    };
    return {
      priceShow,
      classes
    };
  }
});
</script>

<style lang="scss">
@import 'index.scss';
</style>
