// src/packages/elevator/elevator.tsx
import React, { FunctionComponent, useRef, useEffect, useState } from 'react'
import './elevator.scss'
import bem from '@/utils/bem'

export interface ElevatorProps {
  height: number | string
  acceptKey: string
  indexList: any
  className: string
  style: React.CSSProperties
  clickItem: (key: string, item: ElevatorData) => void
  clickIndex: (key: string) => void
}
const defaultProps = {
  height: '200px',
  acceptKey: 'title',
  indexList: [],
  className: '',
} as ElevatorProps
interface ElevatorData {
  name: string
  id: number | string
  [key: string]: string | number
}
export const Elevator: FunctionComponent<
  Partial<ElevatorProps> & React.HTMLAttributes<HTMLDivElement>
> = (props) => {
  const { height, acceptKey, indexList, className, clickItem, clickIndex, ...rest } = {
    ...defaultProps,
    ...props,
  }
  const b = bem('elevator')
  const spaceHeight = 23
  const listview = useRef(null)
  const initData = {
    anchorIndex: 0,
    listHeight: [] as number[],
    listGroup: [] as HTMLElement[],
  }
  const touchState = useRef({
    y1: 0,
    y2: 0,
  })
  const [currentIndex, setCurrentIndex] = useState<number>(0)
  const [scrollStart, setScrollStart] = useState<boolean>(false)
  const state = useRef(initData)
  //重置滚动参数
  const resetScrollState = () => {
    state.current.anchorIndex = 0
    setCurrentIndex(0)
    setScrollStart(false)
    touchState.current = {
      y1: 0,
      y2: 0,
    }
  }

  const getData = (el: HTMLElement, name: string): string | void => {
    const prefix = 'data-'
    return el.getAttribute(prefix + name) as string
  }

  const calculateHeight = () => {
    let height = 0

    state.current.listHeight.push(height)
    for (let i = 0; i < state.current.listGroup.length; i++) {
      let item = state.current.listGroup[i]
      height += item.clientHeight
      state.current.listHeight.push(height)
    }
  }

  const scrollTo = (index: number) => {
    if (!index && index !== 0) {
      return
    }

    if (!state.current.listHeight.length) {
      calculateHeight()
    }
    if (index < 0) index = 0

    if (index > state.current.listHeight.length - 2) index = state.current.listHeight.length - 2

    setCurrentIndex(index)
    if (listview.current) {
      listview.current.scrollTo(0, state.current.listHeight[index])
    }
  }

  const touchMove = (e: React.TouchEvent<HTMLDivElement>) => {
    let firstTouch = e.touches[0]
    touchState.current.y2 = firstTouch.pageY
    let delta = ((touchState.current.y2 - touchState.current.y1) / spaceHeight) | 0
    const cacheIndex = state.current.anchorIndex + delta

    setCurrentIndex(cacheIndex)
    scrollTo(cacheIndex)
  }

  const touchEnd = () => {
    resetScrollState()
  }

  const touchStart = (e: React.TouchEvent<HTMLDivElement>) => {
    setScrollStart(true)
    let index = Number(getData(e.target as HTMLElement, 'index'))
    let firstTouch = e.touches[0]
    touchState.current.y1 = firstTouch.pageY
    state.current.anchorIndex = +index
    setCurrentIndex((currentIndex) => currentIndex + index)
    scrollTo(index)

    const target = e.currentTarget as HTMLElement

    target.removeEventListener('touchmove', touchMove, false)
    target.removeEventListener('touchend', touchEnd, false)
    target.addEventListener('touchmove', touchMove, false)
    target.addEventListener('touchend', touchEnd, false)
  }

  const handleClickItem = (key: string, item: ElevatorData) => {
    clickItem && clickItem(key, item)
  }

  const handleClickIndex = (key: string) => {
    clickIndex && clickIndex(key)
  }

  const setListGroup = () => {
    const els = listview.current.querySelectorAll('.nut-elevator__list__item')

    els.forEach((el: HTMLLIElement) => {
      if (el != null && !state.current.listGroup.includes(el)) {
        state.current.listGroup.push(el)
      }
    })
  }
  useEffect(() => {
    if (listview.current) {
      setListGroup()
    }
  }, [listview.current])

  return (
    <div className={`${b()} ${className}`} {...rest}>
      <div
        className={b('list')}
        ref={listview}
        style={{ height: isNaN(+height) ? height : `${height}px` }}
      >
        {indexList.map((item: any) => {
          return (
            <div className={b('list__item')} key={item[acceptKey]}>
              <div className={b('list__item__code')}>{item[acceptKey]}</div>
              <>
                {item.list.map((subitem: any) => {
                  return (
                    <div
                      className={b('list__item__name')}
                      key={subitem['id']}
                      onClick={() => handleClickItem(item[acceptKey], subitem)}
                    >
                      {subitem.name}
                    </div>
                  )
                })}
              </>
            </div>
          )
        })}
      </div>
      {indexList.length && scrollStart ? (
        <div className={b('code', { current: true })}> {indexList[currentIndex][acceptKey]}</div>
      ) : null}
      <div className={b('bars')} onTouchStart={(event) => touchStart(event)}>
        <div className={b('bars__inner')}>
          {indexList.map((item: any, index: number) => {
            return (
              <div
                className={b('bars__inner__item')}
                data-index={index}
                key={item[acceptKey]}
                onClick={() => handleClickIndex(item[acceptKey])}
              >
                {item[acceptKey]}
              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}

Elevator.defaultProps = defaultProps
Elevator.displayName = 'NutElevator'

// src/packages/__VUE/elevator/index.vue
<template>
  <view :class="classes">
    <view
      class="nut-elevator__list"
      ref="listview"
      :style="{ height: isNaN(+height) ? height : `${height}px` }"
    >
      <view
        class="nut-elevator__list__item"
        v-for="item in indexList"
        :key="item[acceptKey]"
        :ref="setListGroup"
      >
        <view class="nut-elevator__list__item__code">{{
          item[acceptKey]
        }}</view>
        <view
          class="nut-elevator__list__item__name"
          v-for="subitem in item.list"
          :key="subitem['id']"
          @click="handleClickItem(item[acceptKey], subitem)"
          >{{ subitem.name }}</view
        >
      </view>
    </view>
    <view
      class="nut-elevator__code--current"
      v-show="scrollStart"
      v-if="indexList.length"
      >{{ indexList[currentIndex][acceptKey] }}</view
    >
    <view
      class="nut-elevator__bars"
      @touchstart="touchStart"
      @touchmove.stop.prevent="touchMove"
      @touchend="touchEnd"
    >
      <view class="nut-elevator__bars__inner">
        <view
          class="nut-elevator__bars__inner__item"
          :data-index="index"
          v-for="(item, index) in indexList"
          :key="item[acceptKey]"
          @click="handleClickIndex(item[acceptKey])"
          >{{ item[acceptKey] }}</view
        >
      </view>
    </view>
  </view>
</template>
<script lang="ts">
import { computed, reactive, toRefs, nextTick, ref, Ref } from 'vue';
import { createComponent } from '../../utils/create';
const { componentName, create } = createComponent('elevator');
interface ElevatorData {
  name: string;
  id: number | string;
  [key: string]: string | number;
}
export default create({
  props: {
    height: {
      type: [Number, String],
      default: '200px'
    },
    acceptKey: {
      type: [String],
      default: 'title'
    },
    indexList: {
      type: Array,
      default: () => {
        return [];
      }
    }
  },
  emits: ['click-item', 'click-index'],
  setup(props: any, context: any) {
    const spaceHeight = 23;
    const listview: Ref<any> = ref(null);
    const state = reactive({
      anchorIndex: 0,
      listHeight: [] as number[],
      listGroup: [] as HTMLLIElement[],
      touchState: {
        y1: 0,
        y2: 0
      },
      scrollStart: false,
      currentIndex: 0
    });

    const classes = computed(() => {
      const prefixCls = componentName;
      return {
        [prefixCls]: true
      };
    });

    //重置滚动参数
    const resetScrollState = () => {
      state.anchorIndex = 0;
      state.listHeight = [];
      state.listGroup = [];
      state.currentIndex = 0;
      state.scrollStart = false;
      state.touchState = {
        y1: 0,
        y2: 0
      };
    };

    const getData = (el: HTMLElement, name: string): string | void => {
      const prefix = 'data-';
      return el.getAttribute(prefix + name) as string;
    };

    const setListGroup = (el: HTMLLIElement) => {
      nextTick(() => {
        if (!state.listGroup.includes(el) && el != null) {
          state.listGroup.push(el);
        }
      });
    };

    const calculateHeight = () => {
      let height = 0;
      state.listHeight.push(height);
      for (let i = 0; i < state.listGroup.length; i++) {
        let item = state.listGroup[i];
        height += item.clientHeight;
        state.listHeight.push(height);
      }
    };

    const scrollTo = (index: number) => {
      if (!index && index !== 0) {
        return;
      }
      if (!state.listHeight.length) {
        calculateHeight();
      }
      if (index < 0) index = 0;
      if (index > state.listHeight.length - 2)
        index = state.listHeight.length - 2;
      state.currentIndex = index;
      listview.value.scrollTo(0, state.listHeight[index]);
    };

    const touchStart = (e: TouchEvent) => {
      state.scrollStart = true;
      let index = getData(e.target as HTMLElement, 'index');
      let firstTouch = e.touches[0];
      state.touchState.y1 = firstTouch.pageY;
      state.anchorIndex = +index;
      state.currentIndex = +index;
      console.log(state.currentIndex);
      scrollTo(+index);
    };

    const touchMove = (e: TouchEvent) => {
      let firstTouch = e.touches[0];
      state.touchState.y2 = firstTouch.pageY;
      let delta =
        ((state.touchState.y2 - state.touchState.y1) / spaceHeight) | 0;
      state.currentIndex = state.anchorIndex + delta;
      scrollTo(state.currentIndex);
    };

    const touchEnd = () => {
      resetScrollState();
    };

    const handleClickItem = (key: string, item: ElevatorData) => {
      context.emit('click-item', key, item);
    };

    const handleClickIndex = (key: string) => {
      context.emit('click-index', key);
    };

    return {
      classes,
      ...toRefs(state),
      setListGroup,
      listview,
      touchStart,
      touchMove,
      touchEnd,
      handleClickItem,
      handleClickIndex
    };
  }
});
</script>

<style lang="scss" scoped>
@import 'index.scss';
</style>
